//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaractesristicaFisicaVO
    {
        public int CodigoCARACTERISTICAFISICA { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public Nullable<int> CodigoTipoCor { get; set; }
        public string Altura { get; set; }
        public string Peso { get; set; }
        public Nullable<int> CodigoTipoCabelo { get; set; }
        public Nullable<int> CodigoTipoOlho { get; set; }
        public string Sinais { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual FuncionariosVO FuncionariosVO { get; set; }
        public virtual TipoCabeloVO TipoCabeloVO { get; set; }
        public virtual TipoCorVO TipoCorVO { get; set; }
        public virtual TipoOlhoVO TipoOlhoVO { get; set; }
    }
}
