//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosAdmissaoVO
    {
        public int CodigoAdmissao { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public Nullable<int> CodigoTipoCargo { get; set; }
        public Nullable<int> CodigoTipoSecao { get; set; }
        public string SalarioInicial { get; set; }
        public string Comissao { get; set; }
        public Nullable<int> CodigoTipoTarefa { get; set; }
        public Nullable<int> CodigoTipoFormaPagamento { get; set; }
        public string HorarioTrabalhoInicio { get; set; }
        public string HorarioTrabalhoFim { get; set; }
        public string IntervaloAlmocoInicio { get; set; }
        public string IntervaloAlmocoFim { get; set; }
        public string DescansoSemanalInicio { get; set; }
        public string DescansoSemanalFim { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual FuncionariosVO FuncionariosVO { get; set; }
        public virtual TipoCargoVO TipoCargoVO { get; set; }
        public virtual TipoFormaPagamentoVO TipoFormaPagamentoVO { get; set; }
        public virtual TipoSecaoVO TipoSecaoVO { get; set; }
        public virtual TipoTarefaVO TipoTarefaVO { get; set; }
    }
}
