//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoVO
    {
        public int CodigoDocumento { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public string NumeroIdentidade { get; set; }
        public string NumeroCarteiraTrabalho { get; set; }
        public string NumeroSerie { get; set; }
        public string NumeroCertificadoReservista { get; set; }
        public string Categoria { get; set; }
        public string NumeroCPF { get; set; }
        public string TituloEleitor { get; set; }
        public string NumeroCarteiraSaude { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual FuncionariosVO FuncionariosVO { get; set; }
    }
}
