//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaVO
    {
        public EmpresaVO()
        {
            this.FuncionariosVO = new HashSet<FuncionariosVO>();
        }
    
        public int CodigoEmpresa { get; set; }
        public Nullable<int> CodigoEndereco { get; set; }
        public Nullable<int> CodigoContato { get; set; }
        public string CNJP { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string InscricaoEstadual { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual ICollection<FuncionariosVO> FuncionariosVO { get; set; }
        public virtual ContatoVO ContatoVO { get; set; }
        public virtual EnderecoVO EnderecoVO { get; set; }
    }
}
