//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionariosVO
    {
        public FuncionariosVO()
        {
            this.DocumentoVO = new HashSet<DocumentoVO>();
            this.DocumentoEstrangeiroVO = new HashSet<DocumentoEstrangeiroVO>();
            this.DocumentoPIS = new HashSet<DocumentoPISVO>();
            this.DocumentoFundoGarantiaVO = new HashSet<DocumentoFundoGarantiaVO>();
            this.DependenteVO = new HashSet<DependenteVO>();
            this.CaractesristicaFisicaVO = new HashSet<CaractesristicaFisicaVO>();
            this.DadosAdmissaoVO = new HashSet<DadosAdmissaoVO>();
            this.DadosDemissaoVO = new HashSet<DadosDemissaoVO>();
            this.FeriasVO = new HashSet<FeriasVO>();
            this.AcidenteTrabalhoVO = new HashSet<AcidenteTrabalhoVO>();
            this.AlteracaoCargoSalariorVO = new HashSet<AlteracaoCargoSalariorVO>();
            this.ContribuicaoSindicalVO = new HashSet<ContribuicaoSindicalVO>();
        }
    
        public int CodigoFuncionario { get; set; }
        public Nullable<int> CodigoEndereco { get; set; }
        public Nullable<int> CodigoEmpresa { get; set; }
        public Nullable<int> CodigoContato { get; set; }
        public string NomeFuncionario { get; set; }
        public Nullable<int> NumeroOrdemMatricula { get; set; }
        public Nullable<int> NumeroMatricula { get; set; }
        public string NomePai { get; set; }
        public string NacionalidadePai { get; set; }
        public string NomeMae { get; set; }
        public string NacionalidadeMae { get; set; }
        public string DataNascimento { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public Nullable<int> CodigoEstadoCivil { get; set; }
        public string LocalNascimento { get; set; }
        public string Estado { get; set; }
        public string NomeConjuge { get; set; }
        public Nullable<short> QuantosFilhos { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual ContatoVO ContatoVO { get; set; }
        public virtual EmpresaVO EmpresaVO { get; set; }
        public virtual EnderecoVO EnderecoVO { get; set; }
        public virtual EstadoCivilVO EstadoCivilVO { get; set; }
        public virtual ICollection<DocumentoVO> DocumentoVO { get; set; }
        public virtual ICollection<DocumentoEstrangeiroVO> DocumentoEstrangeiroVO { get; set; }
        public virtual ICollection<DocumentoPISVO> DocumentoPIS { get; set; }
        public virtual ICollection<DocumentoFundoGarantiaVO> DocumentoFundoGarantiaVO { get; set; }
        public virtual ICollection<DependenteVO> DependenteVO { get; set; }
        public virtual ICollection<CaractesristicaFisicaVO> CaractesristicaFisicaVO { get; set; }
        public virtual ICollection<DadosAdmissaoVO> DadosAdmissaoVO { get; set; }
        public virtual ICollection<DadosDemissaoVO> DadosDemissaoVO { get; set; }
        public virtual ICollection<FeriasVO> FeriasVO { get; set; }
        public virtual ICollection<AcidenteTrabalhoVO> AcidenteTrabalhoVO { get; set; }
        public virtual ICollection<AlteracaoCargoSalariorVO> AlteracaoCargoSalariorVO { get; set; }
        public virtual ICollection<ContribuicaoSindicalVO> ContribuicaoSindicalVO { get; set; }
    }
}
