-- TBVRT024_DADOS_DEMISSAO
CREATE PROCEDURE SPVRT094_DADOS_DEMISSAO_PR_INCLUIR
(
	@CODIGO_FUNCIONARIO					int        =      null,
	@DATA_DEMISSAO					datetime       =      null,
	@DATA_REGISTRO					datetime       =      null,
	@CODIGO_TIPO_CARGO				int            =      null,
	@CODIGO_TIPO_SECAO				int            =      null,
	@SALARIO_INICIAL				decimal(8,2)   =      null,
	@COMISSAO						nvarchar(80)   =      null,
	@CODIGO_TIPO_TAREFA				int            =      null,
	@CODIGO_TIPO_FORMA_PAGAMENTO	int            =      null,
	@CODIGO_FORMA_PAGAMENTO			int            =      null,
	@CODIGO_USUARIO_CADASTRO		int            =      null,
	@DATA_CADASTRO					datetime       =      null,
	@CODIGO_USUARIO_ALTERACAO		int            =      null,
	@DATA_ALTERACAO					datetime       =      null,
	@CODIGO_STATUS					int            =      null,

	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN

	INSERT INTO TBVRT024_DADOS_DEMISSAO(
		CODIGO_FUNCIONARIO,
		DATA_DEMISSAO,				
		DATA_REGISTRO,				
		CODIGO_TIPO_CARGO,			
		CODIGO_TIPO_SECAO,
		SALARIO_INICIAL,
		COMISSAO,
		CODIGO_TIPO_TAREFA,
		CODIGO_TIPO_FORMA_PAGAMENTO,
		CODIGO_FORMA_PAGAMENTO,
		DATA_CADASTRO,				
		CODIGO_USUARIO_ALTERACAO,	
		DATA_ALTERACAO,				
		CODIGO_STATUS								
	)
	VALUES(
		@CODIGO_FUNCIONARIO,
		@DATA_DEMISSAO,				
		@DATA_REGISTRO,				
		@CODIGO_TIPO_CARGO,			
		@CODIGO_TIPO_SECAO,
		@SALARIO_INICIAL,
		@COMISSAO,
		@CODIGO_TIPO_TAREFA,
		@CODIGO_TIPO_FORMA_PAGAMENTO,
		@CODIGO_FORMA_PAGAMENTO,
		@DATA_CADASTRO,				
		@CODIGO_USUARIO_ALTERACAO,	
		@DATA_ALTERACAO,				
		@CODIGO_STATUS							
	)

	IF(@@ERROR <>0)
		BEGIN
			SELECT @C_ERR = @@ERROR
			SELECT @T_ERR = 'ERRO NO INSERT DA TABELA TBVRT024_DADOS_DEMISSAO.'
			RETURN
		END
	ELSE
		BEGIN
			SELECT @C_ERR = 0
			SELECT @T_ERR = 'DADOS DEMISSAO INSERIDO COM SUCESSO.'
			RETURN
		END
END