USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT053_TIPO_PARENTESCO_PR_SELECIONAR]    Script Date: 28/08/2014 18:11:41 ******/
DROP PROCEDURE [dbo].[SPVRT053_TIPO_PARENTESCO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT053_TIPO_PARENTESCO_PR_SELECIONAR]    Script Date: 28/08/2014 18:11:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT053_TIPO_PARENTESCO_PR_SELECIONAR]
(
	@CODIGO_TIPO_PARENTESCO		 INT = NULL
)
AS
BEGIN

	SELECT * FROM TBVRT014_TIPO_PARENTESCO WHERE 
		(CODIGO_TIPO_PARENTESCO = @CODIGO_TIPO_PARENTESCO OR @CODIGO_TIPO_PARENTESCO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT014_TIPO_PARENTESCO.' as Mensagem 
		END
	RETURN

END

GO


