CREATE PROCEDURE SPVRT078_TIPO_CARGO_PR_INCLUIR
(
    @DESCRICAO            nvarchar(80)     =    null,
    @CODIGO_USUARIO_CADASTRO int           =    null,
    @DATA_CADASTRO        datetime         =    null,
    @CODIGO_USUARIO_ALTERACAO int          =    null,
    @CODIGO_ALTERACAO     datetime         =    null,
    @CODIGO_STATUS        int              =    null,

	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN

	INSERT INTO TBVRT020_TIPO_CARGO(
		DESCRICAO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		CODIGO_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@DESCRICAO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@CODIGO_ALTERACAO,
		@CODIGO_STATUS
	)

	IF(@@ERROR <>0)
		BEGIN
			SELECT @C_ERR = @@ERROR
			SELECT @T_ERR = 'ERRO NO SELECT DA TABELA TBVRT020_TIPO_CARGO.'
			RETURN
		END
	ELSE
		BEGIN
			SELECT @C_ERR = 0
			SELECT @T_ERR = 'TIPO CARGO INSERIDO COM SUCESSO.'
			RETURN
		END
END