USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT045_TIPO_BENEFICIO_PR_SELECIONAR]    Script Date: 11/09/2014 00:35:44 ******/
DROP PROCEDURE [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT045_TIPO_BENEFICIO_PR_SELECIONAR]    Script Date: 11/09/2014 00:35:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]
(
	@CODIGO_SINDICATO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT029_SINDICATO WHERE 
		(CODIGO_SINDICATO = @CODIGO_SINDICATO OR @CODIGO_SINDICATO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT029_SINDICATO.' as Mensagem 
		END
	RETURN	
END


GO


