USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT163_TIPO_BANCO_PR_SELECIONAR]    Script Date: 31/08/2014 17:23:08 ******/
DROP PROCEDURE [dbo].[SPVRT163_TIPO_BANCO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT163_TIPO_BANCO_PR_SELECIONAR]    Script Date: 31/08/2014 17:23:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT163_TIPO_BANCO_PR_SELECIONAR]
(
	@CODIGO_BANCO		 INT = NULL,
	@NOME_BANCO			 NVARCHAR(100) = NULL,
	@NUMERO_BANCO		 NVARCHAR(100) = NULL
)
AS
BEGIN
			
			SELECT 
				CODIGO_BANCO,
				NUMERO_BANCO,
				NOME_BANCO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM TBVRT044_TIPO_BANCO
			WHERE 
				(CODIGO_BANCO = @CODIGO_BANCO OR @CODIGO_BANCO IS NULL) AND
				(NOME_BANCO  LIKE '%'+ @NOME_BANCO + '%' OR @NOME_BANCO IS NULL) AND
				(NUMERO_BANCO = @NUMERO_BANCO OR @NUMERO_BANCO IS NULL)
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS.' as Mensagem 
				END
			RETURN
		
END




GO


