-- TBVRT023_TIPO_FORMA_PAGAMENTO
CREATE PROCEDURE SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR
(
	@CODIGO_TIPO_FORMA_PAGAMENTO INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_FORMA_PAGAMENTO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT023_TIPO_FORMA_PAGAMENTO WHERE CODIGO_TIPO_FORMA_PAGAMENTO = @CODIGO_TIPO_FORMA_PAGAMENTO

			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO DELETE DA TABELA TBVRT023_TIPO_FORMA_PAGAMENTO.'
				END
			ELSE
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'TIPO FORMA PAGAMENTO EXCLUIDO COM SUCESSO.'
				END
			RETURN
		END
END