CREATE PROCEDURE SPVRT077_TIPO_CARGO_PR_SELECIONAR
(
	@CODIGO_TIPO_CARGO	 INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	SELECT * FROM TBVRT020_TIPO_CARGO WHERE 
		(CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO OR @CODIGO_TIPO_CARGO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT020_TIPO_CARGO.' as Mensagem 
		END
	RETURN
END