CREATE PROCEDURE SPVRT047_TIPO_BENEFICIO_PR_ALTERAR
(
	@CODIGO_TIPO_BENEFICIO	int          =      NULL,
	@DESCRICAO            nvarchar(80)   =      null,
    @CODIGO_USUARIO_CADASTRO int         =      null,
    @DATA_CADASTRO        datetime       =      null,
    @CODIGO_USUARIO_ALTERACAO int      =      null,
    @DATA_ALTERACAO     datetime       =      null,
    @CODIGO_STATUS        int            =      null,

	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_BENEFICIO IS NOT NULL)
		BEGIN
			UPDATE TBVRT012_TIPO_BENEFICIO SET
				DESCRICAO = @DESCRICAO,
				CODIGO_USUARIO_CADASTRO = @CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO = @DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO = @CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO = @DATA_ALTERACAO,
				CODIGO_STATUS = @CODIGO_STATUS
			WHERE
				CODIGO_TIPO_BENEFICIO = @CODIGO_TIPO_BENEFICIO
			
			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO UPDATE DA TABELA TBVRT012_TIPO_BENEFICIO.'
					RETURN
				END
			ELSE
				BEGIN
					SELECT @C_ERR = 0
					SELECT @T_ERR = 'TIPO BENEFICIO ALTERADO COM SUCESSO.'
					RETURN
				END
		END
END