USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT022_FUNCIONARIO_PR_INCLUIR]    Script Date: 28/08/2014 23:06:10 ******/
DROP PROCEDURE [dbo].[SPVRT022_FUNCIONARIO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT022_FUNCIONARIO_PR_INCLUIR]    Script Date: 28/08/2014 23:06:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT022_FUNCIONARIO_PR_INCLUIR]
(
@NUMERO_ORDEM_MATRICULA_FUNCIONARIO		INT = NULL,
@NUMERO_MATRICULA_FUNCIONARIO			INT = NULL,
@NOME_FUNCIONARIO_FUNCIONARIO			NVARCHAR(100) = NULL,
@DATA_NASCIMENTO_FUNCIONARIO			DATETIME = NULL,
@LOCAL_NASCIMENTO_FUNCIONARIO			INT = NULL,
@CODIGO_ESTADO_CIVIL_FUNCIONARIO		INT = NULL,
@NOME_CONJUGE_FUNCIONARIO				NVARCHAR(100) = NULL,
@QUANTOS_FILHOS_FUNCIONARIO				SMALLINT = NULL,
@CODIGO_TIPO_ENDERECO_FUNCIONARIO		INT = NULL,
@CODIGO_TIPO_LOGRADOURO_FUNCIONARIO		INT = NULL,
@LOGRADOURO_FUNCIONARIO					NVARCHAR(120) = NULL,
@NUMERO_FUNCIONARIO						NVARCHAR(8) = NULL,
@BAIRRO_FUNCIONARIO						NVARCHAR(80) = NULL,
@COMPLEMENTO_FUNCIONARIO				NVARCHAR(80) = NULL,
@CEP_FUNCIONARIO						CHAR(8) = NULL,
@NOME_PAI_FUNCIONARIO					NVARCHAR(100) = NULL,
@NACIONALIDADE_PAI_FUNCIONARIO			INT = NULL,
@NOME_MAE_FUNCIONARIO					NVARCHAR(100) = NULL,
@NACIONALIDADE_MAE_FUNCIONARIO			INT = NULL,
@NUMERO_IDENTIDADE						NVARCHAR(11) = NULL,
@NUMERO_CARTEIRA_TRABALHO				NVARCHAR(15) = NULL,
@NUMERO_SERIE							NVARCHAR(15) = NULL,
@NUMERO_CERTIFICADO_RESERVISTA			NVARCHAR(15) = NULL,
@CATEGORIA								NVARCHAR(15) = NULL,
@NUMERO_CPF								NVARCHAR(11) = NULL,
@TITULO_ELEITOR							NVARCHAR(15) = NULL,
@NUMERO_CARTEIRA_SAUDE					NVARCHAR(15) = NULL,
@NUMERO_CBO								NVARCHAR(80) = NULL,
@NUMERO_CARTEIRA_19						NVARCHAR(80) = NULL,
@NUMERO_RESISTRO_GERAL					NVARCHAR(80) = NULL,
@CASADO_BRASILEIRO						CHAR(1) = NULL,
@NUTURALIZADO							CHAR(1) = NULL,
@FILHO_BRASILEIRO						CHAR(1) = NULL,
@DATA_CHEGADA_BRASIL					DATETIME = NULL,
@DATA_CADASTRO_PIS						DATETIME = NULL,
@SOB_NUMERO_PIS							NVARCHAR(10) = NULL,
@NUMERO_BANCO_PIS						CHAR(3) = NULL,			
@AGENCIA_PIS							CHAR(10) = NULL,
@DIGITO_PIS								CHAR(2) = NULL,
@CODIGO_TIPO_ENDERECO_PIS				INT = NULL,
@CODIGO_TIPO_LOGRADOURO_PIS				INT = NULL,
@LOGRADOURO_PIS							NVARCHAR(120) = NULL,
@NUMERO_PIS								NVARCHAR(8) = NULL,
@BAIRRO_PIS								NVARCHAR(80) = NULL,
@COMPLEMENTO_PIS						NVARCHAR(80) = NULL,
@CEP_PIS								CHAR(8) = NULL,
@OPTANTE								CHAR(1) = NULL,
@DATA_OPCAO								DATETIME = NULL,
@DATA_RETRATACAO						DATETIME = NULL,
@NUMERO_BANCO_FUNDO_GARANTIA			CHAR(3) = NULL,			
@AGENCIA_FUNDO_GARANTIA					CHAR(10) = NULL,
@DIGITO_FUNDO_GARANTIA					CHAR(2) = NULL,
@ALTURA									DECIMAL(3,2) = NULL,
@PESO									DECIMAL(5,2) = NULL,
@SINAIS									NVARCHAR(80) = NULL,
@CODIGO_TIPO_COR						INT = NULL,
@CODIGO_TIPO_CABELO						INT = NULL,
@CODIGO_TIPO_OLHO						INT = NULL,
@CODIGO_USUARIO_CADASTRO				INT = NULL,
@DATA_CADASTRO							DATETIME = NULL,
@CODIGO_USUARIO_ALTERACAO				INT = NULL,
@DATA_ALTERACAO							DATETIME = NULL,
@CODIGO_STATUS							INT = NULL

)
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION

			
			--INSERT NA TABELA DE ENDERECO COM LIGAÇÃO DE FUNCIONARIO
			DECLARE @CODIGO_ENDERECO_FUNCIONARIO INT
			INSERT INTO TBVRT031_ENDERECO(
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			SET @CODIGO_ENDERECO_FUNCIONARIO = @@IDENTITY;
			--INSERT NA TABELA DE DETALHE ENDERECO COM LIGAÇÃO DE FUNCIONARIO
			INSERT INTO TBVRT032_DETALHE_ENDERECO(
				CODIGO_ENDERECO,
				CODIGO_TIPO_ENDERECO,
				CODIGO_TIPO_LOGRADOURO,
				LOGRADOURO,
				NUMERO,
				BAIRRO,
				COMPLEMENTO,
				CEP,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_ENDERECO_FUNCIONARIO,
				@CODIGO_TIPO_ENDERECO_FUNCIONARIO,
				@CODIGO_TIPO_LOGRADOURO_FUNCIONARIO,
				@LOGRADOURO_FUNCIONARIO,
				@NUMERO_FUNCIONARIO,
				@BAIRRO_FUNCIONARIO,
				@COMPLEMENTO_FUNCIONARIO,
				@CEP_FUNCIONARIO,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			--INSERT NA TABELA DE FUNCIONARIO
			DECLARE @CODIGO_FUNCIONARIO INT
			INSERT INTO TBVRT006_FUNCIONARIO(
				CODIGO_ENDERECO,
				NOME_FUNCIONARIO,
				NUMERO_ORDEM_MATRICULA,
				NUMERO_MATRICULA,
				NOME_PAI,
				NACIONALIDADE_PAI,
				NOME_MAE,
				NACIONALIDADE_MAE,
				DATA_NASCIMENTO,
				CODIGO_ESTADO_CIVIL,
				LOCAL_NASCIMENTO,
				NOME_CONJUGE,
				QUANTOS_FILHOS,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_ENDERECO_FUNCIONARIO,
				@NOME_FUNCIONARIO_FUNCIONARIO,
				@NUMERO_ORDEM_MATRICULA_FUNCIONARIO,
				@NUMERO_MATRICULA_FUNCIONARIO,
				@NOME_PAI_FUNCIONARIO,
				@NACIONALIDADE_PAI_FUNCIONARIO,
				@NOME_MAE_FUNCIONARIO,
				@NACIONALIDADE_MAE_FUNCIONARIO,
				@DATA_NASCIMENTO_FUNCIONARIO,
				@CODIGO_ESTADO_CIVIL_FUNCIONARIO,
				@LOCAL_NASCIMENTO_FUNCIONARIO,
				@NOME_CONJUGE_FUNCIONARIO,
				@QUANTOS_FILHOS_FUNCIONARIO,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)
			SET @CODIGO_FUNCIONARIO = @@IDENTITY;

			--INSERT NA TABELA DE DOCUMENTO
			INSERT INTO TBVRT007_DOCUMENTO(
				CODIGO_FUNCIONARIO,
				NUMERO_IDENTIDADE,
				NUMERO_CARTEIRA_TRABALHO,
				NUMERO_SERIE,
				NUMERO_CERTIFICADO_RESERVISTA,
				CATEGORIA,
				NUMERO_CPF,
				TITULO_ELEITOR,
				NUMERO_CARTEIRA_SAUDE,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_FUNCIONARIO,
				@NUMERO_IDENTIDADE,
				@NUMERO_CARTEIRA_TRABALHO,
				@NUMERO_SERIE,
				@NUMERO_CERTIFICADO_RESERVISTA,
				@CATEGORIA,
				@NUMERO_CPF,
				@TITULO_ELEITOR,
				@NUMERO_CARTEIRA_SAUDE,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			--INSER NA TABELA DE DOCUMENTO ESTRAGEIRO
			INSERT INTO TBVRT008_DOCUMENTO_ESTRANGEIRO(
				CODIGO_FUNCIONARIO,
				NUMERO_CBO,
				NUMERO_CARTEIRA_19,
				NUMERO_RESISTRO_GERAL,
				CASADO_BRASILEIRO,
				NUTURALIZADO,
				FILHO_BRASILEIRO,
				DATA_CHEGADA_BRASIL,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_FUNCIONARIO,
				@NUMERO_CBO,
				@NUMERO_CARTEIRA_19,
				@NUMERO_RESISTRO_GERAL,
				@CASADO_BRASILEIRO,
				@NUTURALIZADO,
				@FILHO_BRASILEIRO,
				@DATA_CHEGADA_BRASIL,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			--INSERT NA TABELA DE ENDERECO PARA A TABELA DE DOCUMENTO PIS BANCO
			DECLARE @CODIGO_ENDERECO_PIS INT
			INSERT INTO TBVRT031_ENDERECO(
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)
			SET @CODIGO_ENDERECO_PIS = @@IDENTITY;
			--INSERT NA TABELA DE DETALHE ENDERECO PARA A TABELA DE DOCUMENTO PIS BANCO
			INSERT INTO TBVRT032_DETALHE_ENDERECO(
				CODIGO_ENDERECO,
				CODIGO_TIPO_ENDERECO,
				CODIGO_TIPO_LOGRADOURO,
				LOGRADOURO,
				NUMERO,
				BAIRRO,
				COMPLEMENTO,
				CEP,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_ENDERECO_PIS,
				@CODIGO_TIPO_ENDERECO_FUNCIONARIO,
				@CODIGO_TIPO_LOGRADOURO_FUNCIONARIO,
				@LOGRADOURO_FUNCIONARIO,
				@NUMERO_FUNCIONARIO,
				@BAIRRO_FUNCIONARIO,
				@COMPLEMENTO_FUNCIONARIO,
				@CEP_FUNCIONARIO,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)
			--INSERT NA TABELA DE BANCO PIS
			DECLARE @CODIGO_BANCO_PIS INT
			INSERT INTO TBVRT039_BANCO(
				NUMERO_BANCO,
				AGENCIA,
				DIGITO,
				CODIGO_ENDERECO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@NUMERO_BANCO_PIS,
				@AGENCIA_PIS,
				@DIGITO_PIS,
				@CODIGO_ENDERECO_PIS,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)
			SET @CODIGO_BANCO_PIS = @@IDENTITY;

			--INSERT NA TABELA DE DOCUMENTO PIS
			INSERT INTO TBVRT009_DOCUMENTO_PIS(
				DATA_CADASTRO_PIS,
				SOB_NUMERO,
				CODIGO_ENDERECO,
				CODIGO_FUNCIONARIO,
				CODIGO_BANCO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@DATA_CADASTRO_PIS,
				@SOB_NUMERO_PIS,
				@CODIGO_ENDERECO_PIS,
				@CODIGO_FUNCIONARIO,
				@CODIGO_BANCO_PIS,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			--INSERT NA TABELA DE BANCO FUNDO DE GARANTIA
			DECLARE @CODIGO_BANCO_FUNDO_GARANTIA INT
			INSERT INTO TBVRT039_BANCO(
				NUMERO_BANCO,
				AGENCIA,
				DIGITO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@NUMERO_BANCO_PIS,
				@AGENCIA_PIS,
				@DIGITO_PIS,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)
			SET @CODIGO_BANCO_FUNDO_GARANTIA = @@IDENTITY;
			
			--INSERT NA TABELA DE FUNDO DE GARANTIA
			INSERT INTO TBVRT010_DOCUMENTO_FUNDO_GARANTIA(
				CODIGO_FUNCIONARIO,
				OPTANTE,
				DATA_OPCAO,
				DATA_RETRATACAO,
				CODIGO_BANCO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_FUNCIONARIO,
				@OPTANTE,
				@DATA_OPCAO,
				@DATA_RETRATACAO,
				@CODIGO_BANCO_FUNDO_GARANTIA,
				@CODIGO_USUARIO_CADASTRO,
				GETDATE(),
				NULL,
				NULL,
				@CODIGO_STATUS
			)

			--INSERT NA TABELA DE CARACTERISTICA FISICA
			INSERT INTO TBVRT015_CARACTERISTICA_FISICA(
				CODIGO_FUNCIONARIO,
				CODIGO_TIPO_COR,
				ALTURA,
				PESO,
				CODIGO_TIPO_CABELO,
				CODIGO_TIPO_OLHO,
				SINAIS,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			)
			VALUES(
				@CODIGO_FUNCIONARIO,
				@CODIGO_TIPO_COR,
				@ALTURA,
				@PESO,
				@CODIGO_TIPO_CABELO,
				@CODIGO_TIPO_OLHO,
				@SINAIS,
				@CODIGO_USUARIO_CADASTRO,
				@DATA_CADASTRO,
				@CODIGO_USUARIO_ALTERACAO,
				@DATA_ALTERACAO,
				@CODIGO_STATUS
			)

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION

		DECLARE @ErrorMessage nvarchar(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState int;

		SELECT 
		@ErrorMessage  = ERROR_MESSAGE(), 
		@ErrorSeverity = ERROR_SEVERITY(),
		@ErrorState  = ERROR_STATE();

		RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

	END CATCH
END

GO


