-- TBVRT023_TIPO_FORMA_PAGAMENTO
CREATE PROCEDURE SPVRT090_TIPO_FORMA_PAGAMENTO_PR_INCLUIR
(
	@DESCRICAO					nvarchar(80)	=	null,
	@CODIGO_USUARIO_CADASTRO	int				=	null,
	@DATA_CADASTRO				datetime        =   null,
	@CODIGO_USUARIO_ALTERACAO	int             =   null,
	@DATA_ALTERACAO				datetime        =   null,
	@CODIGO_STATUS				int             =   null
)
AS
BEGIN

	INSERT INTO TBVRT023_TIPO_FORMA_PAGAMENTO(
		DESCRICAO,					
		CODIGO_USUARIO_CADASTRO,	
		DATA_CADASTRO,			
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,			
		CODIGO_STATUS				
	)
	VALUES(
		@DESCRICAO,					
		@CODIGO_USUARIO_CADASTRO,	
		@DATA_CADASTRO,			
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,			
		@CODIGO_STATUS				
	)

	IF(@@ERROR = 0)
	BEGIN
		SELECT * FROM  TBVRT023_TIPO_FORMA_PAGAMENTO
		WHERE CODIGO_TIPO_FORMA_PAGAMENTO = @@IDENTITY
	END	

END