CREATE PROCEDURE SPVRT080_TIPO_CARGO_PR_EXCLUIR
(
	@CODIGO_TIPO_CARGO     INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_CARGO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT020_TIPO_CARGO WHERE CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO

			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO DELETE DA TABELA TBVRT020_TIPO_CARGO.'
				END
			ELSE
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'TIPO CARGO EXCLUIDO COM SUCESSO.'
				END
			RETURN
		END
END