USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT133_TIPO_LOGRADOURO_PR_SELECIONAR]    Script Date: 26/08/2014 09:42:19 ******/
DROP PROCEDURE [dbo].[SPVRT133_TIPO_LOGRADOURO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT133_TIPO_LOGRADOURO_PR_SELECIONAR]    Script Date: 26/08/2014 09:42:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT133_TIPO_LOGRADOURO_PR_SELECIONAR]
(
	@CODIGO_TIPO_LOGRADOURO		 INT = NULL,
	@DESCRICAO			 NVARCHAR(100) = NULL
)
AS
BEGIN
			
			SELECT 
				CODIGO_TIPO_LOGRADOURO,
				DESCRICAO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM TBVRT034_TIPO_LOGRADOURO
			WHERE 
				(CODIGO_TIPO_LOGRADOURO = @CODIGO_TIPO_LOGRADOURO OR @CODIGO_TIPO_LOGRADOURO IS NULL) AND
				(DESCRICAO = @DESCRICAO OR @DESCRICAO IS NULL)
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS.' as Mensagem 
				END
			RETURN
		
END



GO


