USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]    Script Date: 27/09/2014 21:35:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]
(
	@CODIGO_TIPO_SECAO	 INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_SECAO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT021_TIPO_SECAO WHERE CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO

			IF(@@ERROR = 0)
			BEGIN				
				SELECT 'Seção Excluido com Sucesso.' as Mensagem, 1 as CodigoErro
			END	

			IF(@@ERROR <> 0)
			BEGIN				
				SELECT 'Erro ao Excluir o Seção.' as Mensagem, 2 as CodigoErro
			END			
		END
END