USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT005_TIPO_ACESSO_PR_SELECIONAR]    Script Date: 19/09/2014 10:09:02 ******/
DROP PROCEDURE [dbo].[SPVRT005_TIPO_ACESSO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT005_TIPO_ACESSO_PR_SELECIONAR]    Script Date: 19/09/2014 10:09:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT005_TIPO_ACESSO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_ACESSO	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT002_TIPO_ACESSO WHERE 
		(CODIGO_TIPO_ACESSO = @CODIGO_TIPO_ACESSO OR @CODIGO_TIPO_ACESSO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT002_TIPO_ACESSO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT002_TIPO_ACESSO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN	
END

GO


