USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]    Script Date: 27/09/2014 21:37:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT022_TIPO_TAREFA
ALTER PROCEDURE [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]
(
	@CODIGO_TIPO_TAREFA	 INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_TAREFA IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT022_TIPO_TAREFA WHERE CODIGO_TIPO_TAREFA = @CODIGO_TIPO_TAREFA

			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO DELETE DA TABELA TBVRT022_TIPO_TAREFA.'
				END
			ELSE
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'TIPO TAREFA EXCLUIDO COM SUCESSO.'
				END
			RETURN
		END
END