USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT094_DADOS_DEMISSAO_PR_INCLUIR]    Script Date: 16/09/2014 21:56:59 ******/
DROP PROCEDURE [dbo].[SPVRT094_DADOS_DEMISSAO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT094_DADOS_DEMISSAO_PR_INCLUIR]    Script Date: 16/09/2014 21:56:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT024_DADOS_DEMISSAO
CREATE PROCEDURE [dbo].[SPVRT094_DADOS_DEMISSAO_PR_INCLUIR]
(
	@CODIGO_FUNCIONARIO					int        =      null,
	@DATA_DEMISSAO					datetime       =      null,
	@DATA_REGISTRO					datetime       =      null,
	@CODIGO_TIPO_CARGO				int            =      null,
	@CODIGO_TIPO_SECAO				int            =      null,
	@SALARIO_INICIAL				decimal(8,2)   =      null,
	@COMISSAO						nvarchar(80)   =      null,
	@CODIGO_TIPO_TAREFA				int            =      null,
	@CODIGO_TIPO_FORMA_PAGAMENTO	int            =      null,
	@CODIGO_FORMA_PAGAMENTO			int            =      null,
	@CODIGO_USUARIO_CADASTRO		int            =      null,
	@DATA_CADASTRO					datetime       =      null,
	@CODIGO_USUARIO_ALTERACAO		int            =      null,
	@DATA_ALTERACAO					datetime       =      null,
	@CODIGO_STATUS					int            =      null,

	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN

	INSERT INTO TBVRT024_DADOS_DEMISSAO(
		CODIGO_FUNCIONARIO,
		DATA_DEMISSAO,				
		DATA_REGISTRO,				
		CODIGO_TIPO_CARGO,			
		CODIGO_TIPO_SECAO,
		SALARIO_INICIAL,
		COMISSAO,
		CODIGO_TIPO_TAREFA,
		CODIGO_TIPO_FORMA_PAGAMENTO,
		CODIGO_FORMA_PAGAMENTO,
		DATA_CADASTRO,				
		CODIGO_USUARIO_ALTERACAO,	
		DATA_ALTERACAO,				
		CODIGO_STATUS								
	)
	VALUES(
		@CODIGO_FUNCIONARIO,
		@DATA_DEMISSAO,				
		@DATA_REGISTRO,				
		@CODIGO_TIPO_CARGO,			
		@CODIGO_TIPO_SECAO,
		@SALARIO_INICIAL,
		@COMISSAO,
		@CODIGO_TIPO_TAREFA,
		@CODIGO_TIPO_FORMA_PAGAMENTO,
		@CODIGO_FORMA_PAGAMENTO,
		@DATA_CADASTRO,				
		@CODIGO_USUARIO_ALTERACAO,	
		@DATA_ALTERACAO,				
		@CODIGO_STATUS							
	)

	
		DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR UM DADOS DEMISSAO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DEMISSAO';

			SELECT @C_ERR = @@ERROR
			SELECT @T_ERR = 'ERRO NO INSERT DA TABELA TBVRT024_DADOS_DEMISSAO.'
			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR UM DADOS DEMISSAO - CODIGO DO DADOS DEMISSAO' + CAST(@@IDENTITY AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', '' , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DEMISSAO';

			SELECT @C_ERR = 0
			SELECT @T_ERR = 'DADOS DEMISSAO INSERIDO COM SUCESSO.'
			RETURN
		END


END
GO


