USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT085_TIPO_TAREFA_PR_SELECIONAR]    Script Date: 16/09/2014 21:55:46 ******/
DROP PROCEDURE [dbo].[SPVRT085_TIPO_TAREFA_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT085_TIPO_TAREFA_PR_SELECIONAR]    Script Date: 16/09/2014 21:55:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



create PROCEDURE [dbo].[SPVRT085_TIPO_TAREFA_PR_SELECIONAR]
(
	@CODIGO_TIPO_TAREFA	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT022_TIPO_TAREFA WHERE 
		(CODIGO_TIPO_TAREFA = @CODIGO_TIPO_TAREFA OR @CODIGO_TIPO_TAREFA IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT022_TIPO_TAREFA.' as Mensagem 
		END
	RETURN
END


GO


