USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT087_CIDADE_PR_SELECIONAR]    Script Date: 16/09/2014 21:56:06 ******/
DROP PROCEDURE [dbo].[SPVRT087_CIDADE_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT087_CIDADE_PR_SELECIONAR]    Script Date: 16/09/2014 21:56:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT087_CIDADE_PR_SELECIONAR]
(
	@CODIGO_CIDADE		INT = NULL,
	@SIGLA				CHAR(2) = NULL,
	@DESCRICAO			NVARCHAR(120) = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_ESTADO		INT = NULL
)
AS
BEGIN
	
		
	SELECT CID.CODIGO_CIDADE, CID.DESCRICAO, CID.SIGLA FROM TBVRT042_CIDADE CID
	INNER JOIN TBVRT043_ESTADO AS UF
	ON CID.SIGLA = UF.SIGLA
	WHERE
		(CID.CODIGO_CIDADE = @CODIGO_CIDADE OR @CODIGO_CIDADE IS NULL) AND
		(CID.SIGLA = @SIGLA OR @SIGLA IS NULL) AND
		(CID.DESCRICAO = @DESCRICAO OR @DESCRICAO IS NULL) AND
		(UF.CODIGO_ESTADO = @CODIGO_ESTADO OR @CODIGO_ESTADO IS NULL)
		 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT042_CIDADE.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT042_CIDADE - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END



GO


