USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT041_DEPENDENTE_PR_SELECIONAR]    Script Date: 28/09/2014 19:04:50 ******/
DROP PROCEDURE [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]

/****** Object:  StoredProcedure [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]    Script Date: 27/09/2014 21:35:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_SECAO INT = NULL
)

AS
BEGIN
	SELECT * FROM TBVRT021_TIPO_SECAO WHERE 
		(CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO OR @CODIGO_TIPO_SECAO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT021_TIPO_SECAO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT021_TIPO_SECAO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END
