USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT041_DEPENDENTE_PR_SELECIONAR]    Script Date: 28/09/2014 19:04:50 ******/
DROP PROCEDURE [dbo].[SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR]

/****** Object:  StoredProcedure [dbo].[SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR]    Script Date: 27/09/2014 21:39:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT023_TIPO_FORMA_PAGAMENTO
CREATE PROCEDURE [dbo].[SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR]
(
	@CODIGO_TIPO_FORMA_PAGAMENTO INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_FORMA_PAGAMENTO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT023_TIPO_FORMA_PAGAMENTO WHERE CODIGO_TIPO_FORMA_PAGAMENTO = @CODIGO_TIPO_FORMA_PAGAMENTO

			DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO EXCLUIR UM TIPO DE FORMA DE PAGAMENTO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE FORMA DE PAGAMENTO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO EXCLUIR UM TIPO DE FORMA DE PAGAMENTO - CODIGO DO TIPO DE FORMA DE PAGAMENTO' + CAST(@CODIGO_TIPO_FORMA_PAGAMENTO AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE FORMA DE PAGAMENTO';
			RETURN
		END
				
		END
END