USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]    Script Date: 27/09/2014 21:35:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]
(
	@DESCRICAO					nvarchar(80)	=   null,
	@CODIGO_USUARIO_CADASTRO	int				=   null,
	@DATA_CADASTRO				datetime		=	null,
	@CODIGO_USUARIO_ALTERACAO int				=   null,
	@DATA_ALTERACAO			datetime		    =   null,
	@CODIGO_STATUS				int             =	null
)
AS
BEGIN

	INSERT INTO TBVRT021_TIPO_SECAO(
		DESCRICAO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS	
	)
	VALUES(
		@DESCRICAO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)

		IF(@@ERROR = 0)
	BEGIN
		SELECT * FROM  TBVRT021_TIPO_SECAO
		WHERE CODIGO_TIPO_SECAO = @@IDENTITY
	END	

END