USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT171_DADOS_ADMISSAO_PR_SELECIONAR]    Script Date: 02/10/2014 16:45:28 ******/
DROP PROCEDURE [dbo].[SPVRT171_DADOS_ADMISSAO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT171_DADOS_ADMISSAO_PR_SELECIONAR]    Script Date: 02/10/2014 16:45:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT171_DADOS_ADMISSAO_PR_SELECIONAR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL
)
AS
BEGIN

	SELECT
		CODIGO_ADMISSAO,
		CODIGO_FUNCIONARIO,
		DATA_ADMISSAO,
		DATA_REGISTRO,
		CODIGO_TIPO_CARGO,
		CODIGO_TIPO_SECAO,
		SALARIO_INICIAL,
		COMISSAO,
		CODIGO_TIPO_TAREFA,
		CODIGO_TIPO_FORMA_PAGAMENTO,
		HORARIO_TRABALHO_INICIO,
		HORARIO_TRABALHO_FIM,
		INTERVALO_ALMOCO_INICIO,
		INTERVALO_ALMOCO_FIM,
		DESCANSO_SEMANAL_INICIO,
		DESCANSO_SEMANAL_FIM,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	FROM 
		TBVRT019_DADOS_ADMISSAO
	WHERE
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT019_DADOS_ADMISSAO.' as Mensagem 
		END
	RETURN

END




GO


