USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]    Script Date: 23/08/2014 00:27:08 ******/
DROP PROCEDURE [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]    Script Date: 23/08/2014 00:27:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT033_TIPO_ENDERECO
CREATE PROCEDURE [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]
(
	@CODIGO_TIPO_ENDERECO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT033_TIPO_ENDERECO WHERE 
		(CODIGO_TIPO_ENDERECO = @CODIGO_TIPO_ENDERECO OR @CODIGO_TIPO_ENDERECO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT033_TIPO_ENDERECO.' as Mensagem 
		END
	RETURN
END
GO


