USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT050_BENEFICIO_PR_INCLUIR]    Script Date: 03/10/2014 07:16:30 ******/
DROP PROCEDURE [dbo].[SPVRT050_BENEFICIO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT050_BENEFICIO_PR_INCLUIR]    Script Date: 03/10/2014 07:16:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT050_BENEFICIO_PR_INCLUIR]
(
    @CODIGO_TIPO_BENEFICIO  INT    =     NULL,
    @CODIGO_DEPENDENTE		INT    =     NULL,
	@CODIGO_USUARIO_CADASTRO INT    =     NULL
)
AS
BEGIN

	INSERT INTO TBVRT045_BENEFICIO(
		CODIGO_TIPO_BENEFICIO,
		CODIGO_DEPENDENTE
	)
	VALUES(
		@CODIGO_TIPO_BENEFICIO,
		@CODIGO_DEPENDENTE
	)

	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR UM BENEFÍCIO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE BENEFÍCIO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR UM BENEFÍCIO - CODIGO DO BENEFÍCIO' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE BENEFÍCIO';

			SELECT * FROM  TBVRT045_BENEFICIO
			WHERE CODIGO_BENEFICIO = @ID
			RETURN
		END
END
GO


