USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT077_TIPO_CARGO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:46 ******/
DROP PROCEDURE [dbo].[SPVRT077_TIPO_CARGO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT077_TIPO_CARGO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT077_TIPO_CARGO_PR_SELECIONAR]
(
	@CODIGO_TIPO_CARGO	 INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	SELECT * FROM TBVRT020_TIPO_CARGO WHERE 
		(CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO OR @CODIGO_TIPO_CARGO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT020_TIPO_CARGO.' as Mensagem 
		END
	RETURN
END
GO


