USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT041_DEPENDENTE_PR_SELECIONAR]    Script Date: 28/09/2014 19:04:50 ******/
DROP PROCEDURE [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]

/****** Object:  StoredProcedure [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]    Script Date: 27/09/2014 21:35:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]
(
	@CODIGO_TIPO_SECAO	 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_SECAO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT021_TIPO_SECAO WHERE CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO

			DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO EXCLUIR UM TIPO DE SEÇÃO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE SEÇÃO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO EXCLUIR UM TIPO DE SEÇÃO - CODIGO DO TIPO DE SEÇÃO' + CAST(@CODIGO_TIPO_SECAO AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', '' , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE SEÇÃO';
			RETURN
		END	
		END
END