USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT112_CONTRIBUICAO_SINDICAL_PR_EXCLUIR]    Script Date: 14/09/2014 10:13:33 ******/
DROP PROCEDURE [dbo].[SPVRT112_CONTRIBUICAO_SINDICAL_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT112_CONTRIBUICAO_SINDICAL_PR_EXCLUIR]    Script Date: 14/09/2014 10:13:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT028_CONTRIBUICAO_SINDICAL
CREATE PROCEDURE [dbo].[SPVRT112_CONTRIBUICAO_SINDICAL_PR_EXCLUIR]
(
	@CODIGO_CONTRIBUICAO_SINDICAL		 INT = NULL
)
AS
BEGIN
	
	DELETE FROM TBVRT028_CONTRIBUICAO_SINDICAL WHERE CODIGO_CONTRIBUICAO_SINDICAL = @CODIGO_CONTRIBUICAO_SINDICAL
END

GO


