USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT086_ESTADO_PR_SELECIONAR]    Script Date: 16/09/2014 21:55:54 ******/
DROP PROCEDURE [dbo].[SPVRT086_ESTADO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT086_ESTADO_PR_SELECIONAR]    Script Date: 16/09/2014 21:55:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT086_ESTADO_PR_SELECIONAR]
(
	@CODIGO_ESTADO	 INT = NULL,
	@SIGLA			 CHAR(2) = NULL,
	@DESCRICAO		 NVARCHAR(120) = NULL
)
AS
BEGIN
	
		
	SELECT * FROM TBVRT043_ESTADO WHERE
		(CODIGO_ESTADO = @CODIGO_ESTADO OR @CODIGO_ESTADO IS NULL) AND
		(SIGLA = @SIGLA OR @SIGLA IS NULL) AND
		(DESCRICAO = @DESCRICAO OR @DESCRICAO IS NULL)

		 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT043_ESTADO.' as Mensagem 
		END
	RETURN
END



GO


