USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]    Script Date: 27/09/2014 21:35:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT021_TIPO_SECAO
ALTER PROCEDURE [dbo].[SPVRT084_TIPO_SECAO_PR_EXCLUIR]
(
	@CODIGO_TIPO_SECAO	 INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_SECAO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT021_TIPO_SECAO WHERE CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO

			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO DELETE DA TABELA TBVRT021_TIPO_SECAO.'
				END
			ELSE
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'TIPO SECAO EXCLUIDO COM SUCESSO.'
				END
			RETURN
		END
END