USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT168_LOG_PR_INCLUIR]    Script Date: 01/10/2014 11:08:49 ******/
DROP PROCEDURE [dbo].[SPVRT168_LOG_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT168_LOG_PR_INCLUIR]    Script Date: 01/10/2014 11:08:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT168_LOG_PR_INCLUIR]
(
    @TIPO_LOG					CHAR(1) = NULL,
	@DESCRICAO					NVARCHAR(120) = NULL,
	@CODIGO_USUARIO_EXECUCAO	INT = NULL,
	@METODO						NVARCHAR(120) = NULL
)
AS
BEGIN

	INSERT INTO TBVRT047_LOG(
		TIPO_LOG,
		DESCRICAO,
		CODIGO_USUARIO_EXECUCAO,
		METODO
	)
	VALUES(
		@TIPO_LOG,
		@DESCRICAO,
		@CODIGO_USUARIO_EXECUCAO,
		@METODO
	)

END





GO


