USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:23 ******/
DROP PROCEDURE [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT113_SINDICATO_PR_SELECIONAR]
(
	@CODIGO_SINDICATO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT029_SINDICATO WHERE 
		(CODIGO_SINDICATO = @CODIGO_SINDICATO OR @CODIGO_SINDICATO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT029_SINDICATO.' as Mensagem 
		END
	RETURN	
END



GO


