USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT080_TIPO_CARGO_PR_EXCLUIR]    Script Date: 27/09/2014 21:30:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SPVRT080_TIPO_CARGO_PR_EXCLUIR]
(
	@CODIGO_TIPO_CARGO     INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_CARGO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT020_TIPO_CARGO WHERE CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO

			IF(@@ERROR = 0)
			BEGIN				
				SELECT 'Cargo Excluido com Sucesso.' as Mensagem, 1 as CodigoErro
			END	

			IF(@@ERROR <> 0)
			BEGIN				
				SELECT 'Erro ao Excluir o Cargo.' as Mensagem, 2 as CodigoErro
			END			
		END
END