USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]    Script Date: 26/09/2014 17:12:45 ******/
DROP PROCEDURE [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]    Script Date: 26/09/2014 17:12:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT081_TIPO_SECAO_PR_SELECIONAR]
(
	@CODIGO_TIPO_SECAO INT = NULL
)

AS
BEGIN
	SELECT * FROM TBVRT021_TIPO_SECAO WHERE 
		(CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO OR @CODIGO_TIPO_SECAO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT021_TIPO_SECAO.' as Mensagem 
		END
	RETURN
END


GO


