USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]    Script Date: 16/09/2014 21:56:15 ******/
DROP PROCEDURE [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]    Script Date: 16/09/2014 21:56:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT022_TIPO_TAREFA
CREATE PROCEDURE [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]
(
	@CODIGO_TIPO_TAREFA	 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_TAREFA IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT022_TIPO_TAREFA WHERE CODIGO_TIPO_TAREFA = @CODIGO_TIPO_TAREFA

			DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO EXCLUIR UM TIPO DE TAREFA - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE TAREFA';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO EXCLUIR UM TIPO DE TAREFA - CODIGO DO TIPO DE TAREFA' + CAST(@CODIGO_TIPO_TAREFA AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE TAREFA';
			RETURN
		END
		END
END
GO


