USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:49 ******/
DROP PROCEDURE [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- TBVRT033_TIPO_ENDERECO
CREATE PROCEDURE [dbo].[SPVRT129_TIPO_ENDERECO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_ENDERECO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT033_TIPO_ENDERECO WHERE 
		(CODIGO_TIPO_ENDERECO = @CODIGO_TIPO_ENDERECO OR @CODIGO_TIPO_ENDERECO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT033_TIPO_ENDERECO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT033_TIPO_ENDERECO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END


GO


