USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_USUARIOS_PR_SELECIONAR]    Script Date: 16/09/2014 21:51:26 ******/
DROP PROCEDURE [dbo].[SPVRT001_USUARIOS_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_USUARIOS_PR_SELECIONAR]    Script Date: 16/09/2014 21:51:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT001_USUARIOS_PR_SELECIONAR]
(
	@CODIGO_USUARIO		 INT = NULL
)
AS
BEGIN
			
			SELECT * FROM TBVRT001_USUARIOS WHERE 
			(CODIGO_USUARIO = @CODIGO_USUARIO OR @CODIGO_USUARIO IS NULL) 
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS.' as Mensagem 
				END
			RETURN
		
END



GO


