USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT003_USUARIOS_PR_ALTERAR]    Script Date: 22/09/2014 02:04:33 ******/
DROP PROCEDURE [dbo].[SPVRT003_USUARIOS_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT003_USUARIOS_PR_ALTERAR]    Script Date: 22/09/2014 02:04:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT003_USUARIOS_PR_ALTERAR]
(
	@CODIGO_USUARIO			  int            =      NULL, 
	@NOME					  nvarchar(80)   =      NULL,
    @MAIL					  nvarchar(120)  =      NULL,
    @CODIGO_TIPO_ACESSO		  int            =      NULL,
    @CODIGO_USUARIO_ALTERACAO int			 =      NULL,
    @DATA_ALTERACAO			  datetime       =      NULL
)
AS
BEGIN
	IF(@CODIGO_USUARIO IS NOT NULL)
		BEGIN
			UPDATE TBVRT001_USUARIOS SET
				NOME = @NOME,
				MAIL = @MAIL,
				CODIGO_TIPO_ACESSO = @CODIGO_TIPO_ACESSO,
				CODIGO_USUARIO_ALTERACAO = @CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO = @DATA_ALTERACAO
			WHERE
				CODIGO_USUARIO = @CODIGO_USUARIO
			
			IF(@@ERROR <>0)
				BEGIN
					SELECT @@ERROR as Erro, 'ERRO NO UPDATE DA TABELA TBVRT001_USUARIOS.' as Mensagem
					RETURN
				END
			ELSE
				BEGIN
					SELECT * FROM TBVRT001_USUARIOS WHERE CODIGO_USUARIO = @CODIGO_USUARIO
					RETURN
				END
		END
END

GO


