USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT065_TIPO_CABELO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:28 ******/
DROP PROCEDURE [dbo].[SPVRT065_TIPO_CABELO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT065_TIPO_CABELO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT065_TIPO_CABELO_PR_SELECIONAR]
(
	@CODIGO_TIPO_CABELO	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT017_TIPO_CABELO WHERE 
		(CODIGO_TIPO_CABELO = @CODIGO_TIPO_CABELO OR @CODIGO_TIPO_CABELO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT017_TIPO_CABELO.' as Mensagem 
		END
	RETURN
END


GO


