USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]    Script Date: 16/09/2014 21:55:23 ******/
DROP PROCEDURE [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]    Script Date: 16/09/2014 21:55:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT021_TIPO_SECAO
CREATE PROCEDURE [dbo].[SPVRT082_TIPO_SECAO_PR_INCLUIR]
(
	@DESCRICAO					nvarchar(80)	=   null,
	@CODIGO_USUARIO_CADASTRO	int				=   null,
	@DATA_CADASTRO				datetime		=	null,
	@CODIGO_USUARIO_ATUALIZACAO int				=   null,
	@DATA_ALTERACAO			datetime        =   null,
	@CODIGO_STATUS				int             =	null,

	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN

	INSERT INTO TBVRT021_TIPO_SECAO(
		DESCRICAO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS	
	)
	VALUES(
		@DESCRICAO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ATUALIZACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)

	IF(@@ERROR <>0)
		BEGIN
			SELECT @C_ERR = @@ERROR
			SELECT @T_ERR = 'ERRO NO INSERT DA TABELA TBVRT021_TIPO_SECAO.'
			RETURN
		END
	ELSE
		BEGIN
			SELECT @C_ERR = 0
			SELECT @T_ERR = 'TIPO SECAO INSERIDO COM SUCESSO.'
			RETURN
		END
END
GO


