USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT004_USUARIOS_PR_EXCLUIR]    Script Date: 21/09/2014 22:55:56 ******/
DROP PROCEDURE [dbo].[SPVRT004_USUARIOS_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT004_USUARIOS_PR_EXCLUIR]    Script Date: 21/09/2014 22:55:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT004_USUARIOS_PR_EXCLUIR]
(
	@CODIGO_USUARIO		 INT = NULL
)
AS
BEGIN
	IF(@CODIGO_USUARIO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT001_USUARIOS WHERE CODIGO_USUARIO = @CODIGO_USUARIO

			IF(@@ERROR <> 0)
				BEGIN
					SELECT @@ERROR as Erro, 'ERRO NO DELETE DA TABELA TBVRT001_USUARIOS.' as Mensagem
				END
			
			RETURN
		END
END

GO


