USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT069_TIPO_OLHO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:37 ******/
DROP PROCEDURE [dbo].[SPVRT069_TIPO_OLHO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT069_TIPO_OLHO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT069_TIPO_OLHO_PR_SELECIONAR]
(
	@CODIGO_TIPO_OLHO	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT018_TIPO_OLHO WHERE 
		(CODIGO_TIPO_OLHO = @CODIGO_TIPO_OLHO OR @CODIGO_TIPO_OLHO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT018_TIPO_OLHO.' as Mensagem 
		END
	RETURN
END




GO


