USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]    Script Date: 16/09/2014 21:56:15 ******/
DROP PROCEDURE [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]    Script Date: 16/09/2014 21:56:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT022_TIPO_TAREFA
CREATE PROCEDURE [dbo].[SPVRT088_TIPO_TAREFA_PR_EXCLUIR]
(
	@CODIGO_TIPO_TAREFA	 INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_TAREFA IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT022_TIPO_TAREFA WHERE CODIGO_TIPO_TAREFA = @CODIGO_TIPO_TAREFA

			IF(@@ERROR = 0)
			BEGIN				
				SELECT 'Tarefa Excluido com Sucesso.' as Mensagem, 1 as CodigoErro
			END	

			IF(@@ERROR <> 0)
			BEGIN				
				SELECT 'Erro ao Excluir o Tarefa.' as Mensagem, 2 as CodigoErro
			END		
		END
END
GO


