USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT110_CONTRIBUICAO_SINDICAL_PR_INCLUIR]    Script Date: 14/09/2014 00:47:47 ******/
DROP PROCEDURE [dbo].[SPVRT110_CONTRIBUICAO_SINDICAL_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT110_CONTRIBUICAO_SINDICAL_PR_INCLUIR]    Script Date: 14/09/2014 00:47:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- TBVRT028_CONTRIBUICAO_SINDICAL
CREATE PROCEDURE [dbo].[SPVRT110_CONTRIBUICAO_SINDICAL_PR_INCLUIR]
(
	@CODIGO_FUNCIONARIO				int          =       null,
	@PERIODO_ANO					datetime     =       null,
	@CODIGO_SINDICATO				int          =       null,
	@VALOR_RECOLHIDO				nvarchar(80) =       null,
	@CODIGO_USUARIO_CADASTRO		int          =       null,
	@DATA_CADASTRO					datetime     =       null,
	@CODIGO_USUARIO_ALTERACAO		int          =       null,
	@DATA_ALTERACAO					datetime     =       null,
	@CODIGO_STATUS					int          =       null
)
AS
BEGIN

	INSERT INTO TBVRT028_CONTRIBUICAO_SINDICAL(
		CODIGO_FUNCIONARIO,				
		PERIODO_ANO,				
		CODIGO_SINDICATO,			
		VALOR_RECOLHIDO,			
		CODIGO_USUARIO_CADASTRO,	
		DATA_CADASTRO,				
		CODIGO_USUARIO_ALTERACAO,	
		DATA_ALTERACAO,				
		CODIGO_STATUS
	)
	VALUES(
		@CODIGO_FUNCIONARIO,			
		@PERIODO_ANO,			
		@CODIGO_SINDICATO,		
		@VALOR_RECOLHIDO,		
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,			
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,			
		@CODIGO_STATUS
	)

	IF(@@ERROR = 0)
		BEGIN
			SELECT * FROM TBVRT028_CONTRIBUICAO_SINDICAL WHERE CODIGO_CONTRIBUICAO_SINDICAL = @@IDENTITY;
		END
END

GO


