USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]    Script Date: 01/10/2014 10:40:12 ******/
DROP PROCEDURE [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]    Script Date: 01/10/2014 10:40:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]
(
    @NOME					  nvarchar(80)   =      NULL,
    @MAIL					  nvarchar(120)  =      NULL,
    @LOGIN_USUARIO			  nvarchar(80)   =      NULL,
    @SENHA					  nvarchar(80)   =      NULL,
    @CODIGO_TIPO_ACESSO		  int            =      NULL,
    @CODIGO_USUARIO_CADASTRO  int			 =      NULL,
    @DATA_CADASTRO			  datetime       =      NULL,
    @CODIGO_USUARIO_ALTERACAO int			 =      NULL,
    @DATA_ALTERACAO			  datetime       =      NULL,
    @CODIGO_STATUS			  int            =      NULL
)
AS
BEGIN

	INSERT INTO TBVRT001_USUARIOS(
		NOME,
		MAIL,
		LOGIN_USUARIO,
		SENHA,
		CODIGO_TIPO_ACESSO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@NOME,
		@MAIL,
		@LOGIN_USUARIO,
		@SENHA,
		@CODIGO_TIPO_ACESSO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)


	DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR UM USUÁRIO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR UM USUÁRIO - CODIGO DO USUÁRIO' + CAST(@@IDENTITY AS VARCHAR)

			EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', '' , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';

			SELECT CODIGO_USUARIO, NOME, MAIL, LOGIN_USUARIO FROM TBVRT001_USUARIOS
			WHERE CODIGO_USUARIO = @@IDENTITY
			RETURN
		END
END



GO


