USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT061_TIPO_COR_PR_SELECIONAR]    Script Date: 16/09/2014 21:53:51 ******/
DROP PROCEDURE [dbo].[SPVRT061_TIPO_COR_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT061_TIPO_COR_PR_SELECIONAR]    Script Date: 16/09/2014 21:53:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT061_TIPO_COR_PR_SELECIONAR]
(
	@CODIGO_TIPO_COR	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT016_TIPO_COR WHERE 
		(CODIGO_TIPO_COR = @CODIGO_TIPO_COR OR @CODIGO_TIPO_COR IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT016_TIPO_COR.' as Mensagem 
		END
	RETURN
END


GO


