USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT046_TIPO_BENEFICIO_PR_INCLUIR]    Script Date: 16/09/2014 21:53:01 ******/
DROP PROCEDURE [dbo].[SPVRT046_TIPO_BENEFICIO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT046_TIPO_BENEFICIO_PR_INCLUIR]    Script Date: 16/09/2014 21:53:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT046_TIPO_BENEFICIO_PR_INCLUIR]
(
    @CODIGO_CATEGORIA_BENEFICIO int      =      null,
	@DESCRICAO            nvarchar(80)   =      null,
    @CODIGO_USUARIO_CADASTRO int         =      null,
    @DATA_CADASTRO        datetime       =      null,
    @CODIGO_USUARIO_ALTERACAO int      =      null,
    @DATA_ALTERACAO     datetime       =      null,
    @CODIGO_STATUS        int            =      null
)
AS
BEGIN

	INSERT INTO TBVRT012_TIPO_BENEFICIO(
		DESCRICAO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@DESCRICAO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)

	IF(@@ERROR = 0)
	BEGIN
		SELECT * FROM  TBVRT012_TIPO_BENEFICIO
		WHERE CODIGO_TIPO_BENEFICIO = @@IDENTITY
	END	
END



GO


