USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT080_TIPO_CARGO_PR_EXCLUIR]    Script Date: 27/09/2014 21:30:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SPVRT080_TIPO_CARGO_PR_EXCLUIR]
(
	@CODIGO_TIPO_CARGO     INT = NULL,
	@C_ERR INT			 OUTPUT,
	@T_ERR VARCHAR(255)  OUTPUT 
)
AS
BEGIN
	IF(@CODIGO_TIPO_CARGO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT020_TIPO_CARGO WHERE CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO

			IF(@@ERROR <>0)
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'ERRO NO DELETE DA TABELA TBVRT020_TIPO_CARGO.'
				END
			ELSE
				BEGIN
					SELECT @C_ERR = @@ERROR
					SELECT @T_ERR = 'TIPO CARGO EXCLUIDO COM SUCESSO.'
				END
			RETURN
		END
END