USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR]    Script Date: 27/09/2014 21:39:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- TBVRT023_TIPO_FORMA_PAGAMENTO
ALTER PROCEDURE [dbo].[SPVRT092_TIPO_FORMA_PAGAMENTO_PR_EXCLUIR]
(
	@CODIGO_TIPO_FORMA_PAGAMENTO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_FORMA_PAGAMENTO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT023_TIPO_FORMA_PAGAMENTO WHERE CODIGO_TIPO_FORMA_PAGAMENTO = @CODIGO_TIPO_FORMA_PAGAMENTO

			IF(@@ERROR = 0)
			BEGIN				
				SELECT 'Forma de Pagamento Excluido com Sucesso.' as Mensagem, 1 as CodigoErro
			END	

			IF(@@ERROR <> 0)
			BEGIN				
				SELECT 'Erro ao Excluir o Forma de Pagamento.' as Mensagem, 2 as CodigoErro
			END			
		END
END