USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]    Script Date: 21/09/2014 23:28:21 ******/
DROP PROCEDURE [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]    Script Date: 21/09/2014 23:28:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT002_USUARIOS_PR_INCLUIR]
(
    @NOME					  nvarchar(80)   =      NULL,
    @MAIL					  nvarchar(120)  =      NULL,
    @LOGIN_USUARIO			  nvarchar(80)   =      NULL,
    @SENHA					  nvarchar(80)   =      NULL,
    @CODIGO_TIPO_ACESSO		  int            =      NULL,
    @CODIGO_USUARIO_CADASTRO  int			 =      NULL,
    @DATA_CADASTRO			  datetime       =      NULL,
    @CODIGO_USUARIO_ALTERACAO int			 =      NULL,
    @DATA_ALTERACAO			  datetime       =      NULL,
    @CODIGO_STATUS			  int            =      NULL
)
AS
BEGIN

	INSERT INTO TBVRT001_USUARIOS(
		NOME,
		MAIL,
		LOGIN_USUARIO,
		SENHA,
		CODIGO_TIPO_ACESSO,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@NOME,
		@MAIL,
		@LOGIN_USUARIO,
		@SENHA,
		@CODIGO_TIPO_ACESSO,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)

	IF(@@ERROR <>0)
		BEGIN
			SELECT @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS.' as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			SELECT CODIGO_USUARIO, NOME, MAIL, LOGIN_USUARIO FROM TBVRT001_USUARIOS
			WHERE CODIGO_USUARIO = @@IDENTITY
			RETURN
		END
END


GO


