USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT048_TIPO_BENEFICIO_PR_EXCLUIR]    Script Date: 16/09/2014 21:53:23 ******/
DROP PROCEDURE [dbo].[SPVRT048_TIPO_BENEFICIO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT048_TIPO_BENEFICIO_PR_EXCLUIR]    Script Date: 16/09/2014 21:53:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT048_TIPO_BENEFICIO_PR_EXCLUIR]
(
	@CODIGO_TIPO_BENEFICIO		 INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_BENEFICIO IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT012_TIPO_BENEFICIO WHERE CODIGO_TIPO_BENEFICIO = @CODIGO_TIPO_BENEFICIO

			IF(@@ERROR <>0)
			BEGIN				
				SELECT 'ERRO NO DELETE DA TABELA TBVRT001_USUARIOS.' as Mensagem
			END			
		END
END


GO


