USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT161_PAIS_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:13 ******/
DROP PROCEDURE [dbo].[SPVRT161_PAIS_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT161_PAIS_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT161_PAIS_PR_SELECIONAR]
(
	@CODIGO_PAIS		 INT = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@DESCRICAO			 NVARCHAR(100) = NULL
)
AS
BEGIN
			
			SELECT
				CODIGO_PAIS,
				DESCRICAO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO
			FROM TBVRT041_PAIS WHERE 
			(CODIGO_PAIS = @CODIGO_PAIS OR @CODIGO_PAIS IS NULL) AND
			(DESCRICAO = @DESCRICAO OR @DESCRICAO IS NULL)
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT041_PAIS.' as Mensagem
					
					DECLARE @DESC VARCHAR(120)

					SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT041_PAIS - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
					 
				END
			RETURN
		
END



GO


