USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]    Script Date: 28/09/2014 18:41:26 ******/
DROP PROCEDURE [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]    Script Date: 28/09/2014 18:41:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]
(
	@CODIGO_DEPENDENTE		 INT = NULL
)
AS
BEGIN
	IF(@CODIGO_DEPENDENTE IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT011_DEPENDENTE WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE

			IF(@@ERROR <>0)
				BEGIN
					SELECT @@ERROR as Erro, 'ERRO NO DELETE DA TABELA TBVRT011_DEPENDENTE.' as Mensagem
				END
			RETURN
		END
END

GO


