USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]    Script Date: 28/09/2014 18:41:26 ******/
DROP PROCEDURE [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]    Script Date: 28/09/2014 18:41:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT044_DEPENDENTE_PR_EXCLUIR]
(
	@CODIGO_DEPENDENTE		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_DEPENDENTE IS NOT NULL)
		BEGIN
			DELETE FROM TBVRT011_DEPENDENTE WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE


			DECLARE @DESC VARCHAR(120)

			IF(@@ERROR <>0)
				BEGIN

					SET @DESC = 'ERRO AO EXCLUIR UM DEPENDENTE - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE DEPENDENTE';

					SELECT @@ERROR as Erro, @DESC as Mensagem
					RETURN
				END
			ELSE
				BEGIN
			
					SET @DESC = 'SUCESSO AO EXCLUIR UM DEPENDENTE - CODIGO DO DEPENDENTE' + CAST(@CODIGO_DEPENDENTE AS VARCHAR)

					EXEC dbo.SPVRT168_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE DEPENDENTE';

					RETURN
				END
		END
END

GO


