USE [DBVERITHUS]
GO
/****** Object:  StoredProcedure [dbo].[SPVRT061_TIPO_CARGO_PR_SELECIONAR]    Script Date: 27/09/2014 21:30:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT061_TIPO_CARGO_PR_SELECIONAR]
(
	@CODIGO_TIPO_CARGO	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT020_TIPO_CARGO WHERE 
		(CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO OR @CODIGO_TIPO_CARGO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT020_TIPO_CARGO.' as Mensagem 
		END
	RETURN
END

