USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT111_CONTRIBUICAO_SINDICAL_PR_ALTERAR]    Script Date: 14/09/2014 09:31:06 ******/
DROP PROCEDURE [dbo].[SPVRT111_CONTRIBUICAO_SINDICAL_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT111_CONTRIBUICAO_SINDICAL_PR_ALTERAR]    Script Date: 14/09/2014 09:31:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT028_CONTRIBUICAO_SINDICAL
CREATE PROCEDURE [dbo].[SPVRT111_CONTRIBUICAO_SINDICAL_PR_ALTERAR]
(
	@CODIGO_CONTRIBUICAO_SINDICAL	int          =       null,
	@PERIODO_ANO					datetime     =       null,
	@CODIGO_SINDICATO				int          =       null,
	@VALOR_RECOLHIDO				nvarchar(80) =       null,
	@CODIGO_USUARIO_ALTERACAO		int          =       null,
	@DATA_ALTERACAO					datetime     =       null,
	@CODIGO_STATUS					int          =       null
)
AS
BEGIN
	UPDATE TBVRT028_CONTRIBUICAO_SINDICAL SET			
		PERIODO_ANO			= @PERIODO_ANO,		
		CODIGO_SINDICATO	= @CODIGO_SINDICATO,			
		VALOR_RECOLHIDO		= @VALOR_RECOLHIDO,
		CODIGO_USUARIO_ALTERACAO	= @CODIGO_USUARIO_ALTERACAO,	
		DATA_ALTERACAO			= @DATA_ALTERACAO,		
		CODIGO_STATUS		= @CODIGO_STATUS			
	WHERE
		CODIGO_CONTRIBUICAO_SINDICAL = @CODIGO_CONTRIBUICAO_SINDICAL
	
	IF(@@ERROR = 0)
		BEGIN
			SELECT * FROM TBVRT028_CONTRIBUICAO_SINDICAL WHERE CODIGO_CONTRIBUICAO_SINDICAL = @CODIGO_CONTRIBUICAO_SINDICAL;
		END
END
GO


