//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoTech2u.Verithus.VO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoPISVO
    {
        public int CodigoPIS { get; set; }
        public Nullable<System.DateTime> DataCadastroPIS { get; set; }
        public string SOBNumero { get; set; }
        public string SOBBanco { get; set; }
        public Nullable<int> CodigoEndereco { get; set; }
        public Nullable<int> CodigoFuncionario { get; set; }
        public Nullable<int> CodigoBanco { get; set; }
        public Nullable<int> CodigoUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> CodigoUsuarioAlteracao { get; set; }
        public Nullable<int> DataAlteracao { get; set; }
        public Nullable<int> CodigoStatus { get; set; }
    
        public virtual FuncionariosVO FuncionariosVO { get; set; }
        public virtual BancoVO BancoVO { get; set; }
        public virtual EnderecoVO EnderecoVO { get; set; }
    }
}
