INSERT INTO [dbo].[TBVRT040_ESTADO_CIVIL](DESCRICAO) VALUES('Solteiro(a)')
INSERT INTO [dbo].[TBVRT040_ESTADO_CIVIL](DESCRICAO) VALUES('Casado(a)')
INSERT INTO [dbo].[TBVRT040_ESTADO_CIVIL](DESCRICAO) VALUES('Divorciado(a)')
INSERT INTO [dbo].[TBVRT040_ESTADO_CIVIL](DESCRICAO) VALUES('Viúvo(a)')