INSERT INTO [dbo].[TBVRT033_TIPO_ENDERECO](DESCRICAO) VALUES('Casa')
INSERT INTO [dbo].[TBVRT033_TIPO_ENDERECO](DESCRICAO) VALUES('Condominio')
INSERT INTO [dbo].[TBVRT033_TIPO_ENDERECO](DESCRICAO) VALUES('Apartamento')
