INSERT INTO [dbo].[TBVRT038_TIPO_CONTATO](DESCRICAO) VALUES('Comercial')
INSERT INTO [dbo].[TBVRT038_TIPO_CONTATO](DESCRICAO) VALUES('Residencial')
INSERT INTO [dbo].[TBVRT038_TIPO_CONTATO](DESCRICAO) VALUES('Recado')