USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]    Script Date: 27/10/2014 03:19:59 ******/
DROP PROCEDURE [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]    Script Date: 27/10/2014 03:19:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_CADASTRO int = null,
	@CODIGO_FERIAS	int = null
)
AS
BEGIN

	SELECT
		CODIGO_FERIAS,
		CODIGO_FUNCIONARIO,
		CONVERT(varchar, DATA_PERIODO_INICIO, 103) AS DATA_PERIODO_INICIO,
		CONVERT(varchar, DATA_PERIODO_FIM, 103) AS DATA_PERIODO_FIM,
		CONVERT(varchar, DATA_GOZADA_INICIO, 103) AS DATA_GOZADA_INICIO,
		CONVERT(varchar, DATA_GOZADA_FIM, 103) AS DATA_GOZADA_FIM,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	FROM 
		TBVRT025_FERIAS
	WHERE
		(CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO OR @CODIGO_FUNCIONARIO IS NULL) 
		and (CODIGO_FERIAS = @CODIGO_FERIAS OR @CODIGO_FERIAS IS NULL) 

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT025_FERIAS.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT025_FERIAS - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'CONSULTA FERIAS';
			 
		END
	RETURN

END







GO


