USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT038_TIPO_BENEFICIO_PR_EXCLUIR]    Script Date: 09/10/2014 01:09:12 ******/
DROP PROCEDURE [dbo].[SPVRT038_TIPO_BENEFICIO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT038_TIPO_BENEFICIO_PR_EXCLUIR]    Script Date: 09/10/2014 01:09:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT038_TIPO_BENEFICIO_PR_EXCLUIR]
(
	@CODIGO_TIPO_BENEFICIO		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_TIPO_BENEFICIO IS NOT NULL)
		BEGIN
			
			DECLARE @DESC VARCHAR(120)
			IF((SELECT COUNT(0) FROM TBVRT045_BENEFICIO where CODIGO_TIPO_BENEFICIO = @CODIGO_TIPO_BENEFICIO) <= 0)
			BEGIN
			DELETE FROM TBVRT012_TIPO_BENEFICIO WHERE CODIGO_TIPO_BENEFICIO = @CODIGO_TIPO_BENEFICIO
				IF(@@ERROR <>0)
				BEGIN

					SET @DESC = 'ERRO AO EXCLUIR UM TIPO DE BENEFÍCIO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE BENEFÍCIO';

					SELECT @@ERROR as Erro, @DESC as Mensagem
					RETURN
				END
				ELSE
				BEGIN
			
					SET @DESC = 'SUCESSO AO EXCLUIR UM TIPO DE BENEFÍCIO - CODIGO DO TIPO DE BENEFÍCIO' + CAST(@CODIGO_TIPO_BENEFICIO AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE TIPO DE BENEFÍCIO';
					RETURN
				END
			END
			ELSE
			BEGIN
				SELECT 'RELACIONAMENTO' as Erro, 'RELACIONAMENTO COM DEPENDENTE AINDA EXISTE' as Mensagem
				RETURN
			END
		END
END



GO


