USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT054_TIPO_PARENTESCO_PR_SELECIONAR]    Script Date: 16/09/2014 21:53:32 ******/
DROP PROCEDURE [dbo].[SPVRT054_TIPO_PARENTESCO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT054_TIPO_PARENTESCO_PR_SELECIONAR]    Script Date: 16/09/2014 21:53:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT054_TIPO_PARENTESCO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_PARENTESCO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT014_TIPO_PARENTESCO WHERE 
		(CODIGO_TIPO_PARENTESCO = @CODIGO_TIPO_PARENTESCO OR @CODIGO_TIPO_PARENTESCO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT014_TIPO_PARENTESCO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT014_TIPO_PARENTESCO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END

GO


