USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT075_LOG_PR_SELECIONAR]    Script Date: 13/10/2014 06:12:10 ******/
DROP PROCEDURE [dbo].[SPVRT075_LOG_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT075_LOG_PR_SELECIONAR]    Script Date: 13/10/2014 06:12:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT075_LOG_PR_SELECIONAR]
(
	@TIPO_LOG					char(1)				=	NULL,
	@CODIGO_USUARIO_EXECUCAO	int = null,
	@NOME_USUARIO_EXECUCAO		NVARCHAR(80)	= NULL,
	@DATA_GERACAO_INICIO		DATETIME = NULL,
	@DATA_GERACAO_FIM			DATETIME = NULL,
	@METODO						NVARCHAR(120),
	@CODIGO_USUARIO_CADASTRO	INT = NULL
)
AS
BEGIN

	SELECT
		TLOG.TIPO_LOG,
		TLOG.DESCRICAO,
		TLOG.DATA_GERACAO,
		TLOG.CODIGO_USUARIO_EXECUCAO,
		USUA.NOME,
		TLOG.METODO
	FROM 
		TBVRT047_LOG TLOG
		INNER JOIN TBVRT001_USUARIOS USUA
		ON TLOG.CODIGO_USUARIO_EXECUCAO = USUA.CODIGO_USUARIO
	WHERE
		(TLOG.TIPO_LOG = @TIPO_LOG OR @TIPO_LOG IS NULL) AND
		(TLOG.CODIGO_USUARIO_EXECUCAO = @CODIGO_USUARIO_EXECUCAO OR @CODIGO_USUARIO_EXECUCAO IS NULL) AND
		(TLOG.METODO = @METODO OR @METODO IS NULL) AND
		(USUA.NOME = @NOME_USUARIO_EXECUCAO OR @NOME_USUARIO_EXECUCAO IS NULL) AND
		(TLOG.DATA_GERACAO BETWEEN (@DATA_GERACAO_INICIO) AND (@DATA_GERACAO_FIM) OR @DATA_GERACAO_INICIO IS NULL)

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT047_LOG.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT047_LOG - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'CONSULTA DE LOG';
			 
		END
	RETURN

END






GO


