USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT010_DADOS_ADMISSAO_PR_SELECIONAR]    Script Date: 20/10/2014 15:43:32 ******/
DROP PROCEDURE [dbo].[SPVRT010_DADOS_ADMISSAO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT010_DADOS_ADMISSAO_PR_SELECIONAR]    Script Date: 20/10/2014 15:43:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT010_DADOS_ADMISSAO_PR_SELECIONAR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_CADASTRO int = null
)
AS
BEGIN

	SELECT
		DA.CODIGO_ADMISSAO,
		DA.CODIGO_FUNCIONARIO,
		DA.DATA_ADMISSAO,
		CONVERT(NVARCHAR, DA.DATA_ADMISSAO, 103) AS DATA_ADMISSAO_STR,
		DA.DATA_REGISTRO,
		CONVERT(NVARCHAR, DA.DATA_REGISTRO, 103) AS DATA_REGISTRO_STR,
		DA.CODIGO_TIPO_CARGO,
		TG.DESCRICAO AS TIPO_CARGO,
		DA.CODIGO_TIPO_SECAO,
		TS.DESCRICAO AS TIPO_SECAO,
		DA.SALARIO_INICIAL,
		DA.COMISSAO,
		DA.CODIGO_TIPO_TAREFA,
		TT.DESCRICAO AS TIPO_TAREFA,
		DA.CODIGO_TIPO_FORMA_PAGAMENTO,
		TFP.DESCRICAO AS TIPO_FORMA_PAGAMENTO,
		DA.HORARIO_TRABALHO_INICIO,
		DA.HORARIO_TRABALHO_FIM,
		DA.INTERVALO_ALMOCO_INICIO,
		DA.INTERVALO_ALMOCO_FIM,
		DA.DESCANSO_SEMANAL_INICIO,
		DA.DESCANSO_SEMANAL_FIM,
		DA.CODIGO_USUARIO_CADASTRO,
		DA.DATA_CADASTRO,
		DA.CODIGO_USUARIO_ALTERACAO,
		DA.DATA_ALTERACAO,
		DA.CODIGO_STATUS
	FROM 
		TBVRT019_DADOS_ADMISSAO DA
		INNER JOIN TBVRT020_TIPO_CARGO TG ON DA.CODIGO_TIPO_CARGO = TG.CODIGO_TIPO_CARGO
		INNER JOIN TBVRT021_TIPO_SECAO TS ON DA.CODIGO_TIPO_SECAO = TS.CODIGO_TIPO_SECAO
		INNER JOIN TBVRT022_TIPO_TAREFA TT ON DA.CODIGO_TIPO_TAREFA = TT.CODIGO_TIPO_TAREFA
		INNER JOIN TBVRT023_TIPO_FORMA_PAGAMENTO TFP ON DA.CODIGO_TIPO_FORMA_PAGAMENTO = TFP.CODIGO_TIPO_FORMA_PAGAMENTO
		

	WHERE
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT019_DADOS_ADMISSAO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT019_DADOS_ADMISSAO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN

END






GO


