USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT041_TIPO_CABELO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:28 ******/
DROP PROCEDURE [dbo].[SPVRT041_TIPO_CABELO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT041_TIPO_CABELO_PR_SELECIONAR]    Script Date: 16/09/2014 21:54:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT041_TIPO_CABELO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_CABELO	 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT017_TIPO_CABELO WHERE 
		(CODIGO_TIPO_CABELO = @CODIGO_TIPO_CABELO OR @CODIGO_TIPO_CABELO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT017_TIPO_CABELO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT017_TIPO_CABELO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END


GO


