USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT004_CONTRIBUICAO_SINDICAL_PR_ALTERAR]    Script Date: 14/09/2014 09:31:06 ******/
DROP PROCEDURE [dbo].[SPVRT004_CONTRIBUICAO_SINDICAL_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT004_CONTRIBUICAO_SINDICAL_PR_ALTERAR]    Script Date: 14/09/2014 09:31:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- TBVRT028_CONTRIBUICAO_SINDICAL
CREATE PROCEDURE [dbo].[SPVRT004_CONTRIBUICAO_SINDICAL_PR_ALTERAR]
(
	@CODIGO_CONTRIBUICAO_SINDICAL	int          =       null,
	@PERIODO_ANO					datetime     =       null,
	@CODIGO_SINDICATO				int          =       null,
	@VALOR_RECOLHIDO				nvarchar(80) =       null,
	@CODIGO_USUARIO_ALTERACAO		int          =       null,
	@DATA_ALTERACAO					datetime     =       null,
	@CODIGO_STATUS					int          =       null
)
AS
BEGIN
	UPDATE TBVRT028_CONTRIBUICAO_SINDICAL SET			
		PERIODO_ANO			= @PERIODO_ANO,		
		CODIGO_SINDICATO	= @CODIGO_SINDICATO,			
		VALOR_RECOLHIDO		= @VALOR_RECOLHIDO,
		CODIGO_USUARIO_ALTERACAO	= @CODIGO_USUARIO_ALTERACAO,	
		DATA_ALTERACAO			= @DATA_ALTERACAO,		
		CODIGO_STATUS		= @CODIGO_STATUS			
	WHERE
		CODIGO_CONTRIBUICAO_SINDICAL = @CODIGO_CONTRIBUICAO_SINDICAL
	
	DECLARE @DESC VARCHAR(120)

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO ALTERAR UMA CONTRIBUI플O SINDICAL - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'ALTERA플O DE CONTRIBUI플O SINDICAL';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO ALTERAR UMA CONTRIBUI플O SINDICAL - CODIGO DA CONTRIBUI플O SINDICAL' + CAST(@CODIGO_CONTRIBUICAO_SINDICAL AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'ALTERA플O DE CONTRIBUI플O SINDICAL';

			SELECT * FROM TBVRT028_CONTRIBUICAO_SINDICAL 
			WHERE CODIGO_CONTRIBUICAO_SINDICAL = @CODIGO_CONTRIBUICAO_SINDICAL;
			RETURN
		END

END
GO


