USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT070_ACIDENTE_TRABALHO_PR_INCLUIR]    Script Date: 16/11/2014 21:34:16 ******/
DROP PROCEDURE [dbo].[SPVRT070_ACIDENTE_TRABALHO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT070_ACIDENTE_TRABALHO_PR_INCLUIR]    Script Date: 16/11/2014 21:34:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT070_ACIDENTE_TRABALHO_PR_INCLUIR]
(
    @CODIGO_ACIDENTE_TRABALHO		INT = NULL,
	@CODIGO_FUNCIONARIO				INT = NULL,
	@DATA							DATETIME = NULL,
	@ACIDENTE_TRABALHO_LOCAL		TEXT = NULL,
	@CAUSA							TEXT = NULL,
	@DATA_ALTA						DATETIME = NULL,
	@RESULTADO						TEXT = NULL,
	@OBSERVACOES					TEXT = NULL,
	@CODIGO_USUARIO_CADASTRO		INT = NULL,
	@DATA_CADASTRO					DATETIME = NULL,
	@CODIGO_USUARIO_ALTERACAO		INT = NULL,
	@DATA_ALTERACAO					DATETIME = NULL,
	@CODIGO_STATUS					INT = NULL
)
AS
BEGIN

	INSERT INTO TBVRT026_ACIDENTE_TRABALHO(
		CODIGO_FUNCIONARIO,
		DATA,
		ACIDENTE_TRABALHO_LOCAL,
		CAUSA,
		DATA_ALTA,
		RESULTADO,
		OBSERVACOES,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@CODIGO_FUNCIONARIO,
		@DATA,
		@ACIDENTE_TRABALHO_LOCAL,
		@CAUSA,
		@DATA_ALTA,
		@RESULTADO,
		@OBSERVACOES,
		@CODIGO_USUARIO_CADASTRO,
		GETDATE(),
		NULL,
		NULL,
		@CODIGO_STATUS
	)


	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR DADOS DE ACIDENTE DE TRABALHO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE ACIDENTE DE TRABALHO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR DADOS DE ACIDENTE DE TRABALHO - CODIGO DO USUÁRIO: ' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE ACIDENTE DE TRABALHO';

			SELECT
				CODIGO_ACIDENTE_TRABALHO,
				CODIGO_FUNCIONARIO,
				CONVERT(varchar, DATA, 103) AS DATA,
				ACIDENTE_TRABALHO_LOCAL,
				CAUSA,
				CONVERT(varchar, DATA_ALTA, 103) AS DATA_ALTA,
				RESULTADO,
				OBSERVACOES,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM 
				TBVRT026_ACIDENTE_TRABALHO
			WHERE
				CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

			RETURN
		END
END





GO


