USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT032_SINDICATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:23 ******/
DROP PROCEDURE [dbo].[SPVRT032_SINDICATO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT032_SINDICATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:57:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT032_SINDICATO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_SINDICATO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT029_SINDICATO WHERE 
		(CODIGO_SINDICATO = @CODIGO_SINDICATO OR @CODIGO_SINDICATO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT029_SINDICATO.' as Mensagem 

			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT029_SINDICATO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';

		END
	RETURN	
END



GO


