USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT036_TIPO_BANCO_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:30 ******/
DROP PROCEDURE [dbo].[SPVRT036_TIPO_BANCO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT036_TIPO_BANCO_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE [dbo].[SPVRT036_TIPO_BANCO_PR_SELECIONAR]
(
	@CODIGO_BANCO		 INT = NULL,
	@NOME_BANCO			 NVARCHAR(100) = NULL,
	@NUMERO_BANCO		 NVARCHAR(100) = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL
)
AS
BEGIN
			
			SELECT 
				CODIGO_BANCO,
				NUMERO_BANCO,
				NOME_BANCO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM TBVRT044_TIPO_BANCO
			WHERE 
				(CODIGO_BANCO = @CODIGO_BANCO OR @CODIGO_BANCO IS NULL) AND
				(NOME_BANCO  LIKE '%'+ @NOME_BANCO + '%' OR @NOME_BANCO IS NULL) AND
				(NUMERO_BANCO = @NUMERO_BANCO OR @NUMERO_BANCO IS NULL)
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS.' as Mensagem
					
					DECLARE @DESC VARCHAR(120)

					SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT001_USUARIOS - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO'; 


				END
			RETURN
		
END





GO


