USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT020_EMPRESA_PR_INCLUIR]    Script Date: 04/10/2014 09:18:25 ******/
DROP PROCEDURE [dbo].[SPVRT020_EMPRESA_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT020_EMPRESA_PR_INCLUIR]    Script Date: 04/10/2014 09:18:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT020_EMPRESA_PR_INCLUIR]
(
    @CODIGO_EMPRESA				INT = NULL,
	@CNJP						NVARCHAR(14) = NULL,
	@RAZAO_SOCIAL				NVARCHAR(80) = NULL,
	@NOME_FANTASIA				NVARCHAR(80) = NULL,
	@INCRICAO_ESTADUAL			NVARCHAR(80) = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@DATA_CADASTRO				DATETIME,
	@CODIGO_USUARIO_ALTERACAO	INT = NULL,
	@DATA_ALTERACAO				DATETIME,
	@CODIGO_STATUS				INT = NULL
)
AS
BEGIN

	INSERT INTO TBVRT030_EMPRESA(
		CNJP,
		RAZAO_SOCIAL,
		NOME_FANTASIA,
		INCRICAO_ESTADUAL,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@CNJP,
		@RAZAO_SOCIAL,
		@NOME_FANTASIA,
		@INCRICAO_ESTADUAL,
		@CODIGO_USUARIO_CADASTRO,
		GETDATE(),
		NULL,
		NULL,
		@CODIGO_STATUS
	)


	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR DADOS DE EMPRESA - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE EMPRESA';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR DADOS DE EMPRESA - CODIGO DO USUÁRIO' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE EMPRESA';

			SELECT CODIGO_USUARIO, NOME, MAIL, LOGIN_USUARIO FROM TBVRT001_USUARIOS
			WHERE CODIGO_USUARIO = @ID
			RETURN
		END
END





GO


