USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT081_BENEFICIO_PR_SELECIONAR]    Script Date: 26/10/2014 22:46:10 ******/
DROP PROCEDURE [dbo].[SPVRT081_BENEFICIO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT081_BENEFICIO_PR_SELECIONAR]    Script Date: 26/10/2014 22:46:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT081_BENEFICIO_PR_SELECIONAR]
(
    @CODIGO_TIPO_BENEFICIO  INT    =     NULL,
    @CODIGO_DEPENDENTE		INT    =     NULL,
	@CODIGO_USUARIO_CADASTRO INT    =     NULL
)
AS
BEGIN

	SELECT * FROM TBVRT045_BENEFICIO BE
		INNER JOIN TBVRT012_TIPO_BENEFICIO TB
	ON TB.CODIGO_TIPO_BENEFICIO = BE.CODIGO_TIPO_BENEFICIO
	WHERE BE.CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE

END

GO


