USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT072_ALTERACAO_CARGO_SALARIO_PR_ALTERAR]    Script Date: 02/10/2014 16:45:28 ******/
DROP PROCEDURE [dbo].[SPVRT072_ALTERACAO_CARGO_SALARIO_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT072_ALTERACAO_CARGO_SALARIO_PR_ALTERAR]    Script Date: 02/10/2014 16:45:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT072_ALTERACAO_CARGO_SALARIO_PR_ALTERAR]
(
    @CODIGO_ALTERACAO_CARGO_SALARIO		INT = NULL,
	@CODIGO_FUNCIONARIO					INT = NULL,
	@DATA								DATETIME = NULL,
	@CODIGO_TIPO_CARGO					INT = NULL,
	@SALARIO							NVARCHAR(80) = NULL,
	@HORARIO_INICIO						NVARCHAR(80) = NULL,
	@HORARIO_FIM						NVARCHAR(80) = NULL,
	@CODIGO_USUARIO_CADASTRO			INT = NULL,
	@DATA_CADASTRO						DATETIME = NULL,
	@CODIGO_USUARIO_ALTERACAO			INT = NULL,
	@DATA_ALTERACAO						DATETIME = NULL,
	@CODIGO_STATUS						INT = NULL
)
AS
BEGIN

	UPDATE TBVRT027_ALTERACAO_CARGO_SALARIO SET
		DATA								=	@DATA,
		CODIGO_TIPO_CARGO					=	@CODIGO_TIPO_CARGO,
		SALARIO								=	@SALARIO,
		HORARIO_INICIO						=	@HORARIO_INICIO,
		HORARIO_FIM							=	@HORARIO_FIM,
		CODIGO_USUARIO_ALTERACAO			=	@CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO						=	GETDATE(),
		CODIGO_STATUS						=	@CODIGO_STATUS
	WHERE
		CODIGO_ALTERACAO_CARGO_SALARIO = @CODIGO_ALTERACAO_CARGO_SALARIO AND
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO ALTERAR DADOS DE ALTERAÇÃO DE CARGO SALÁRIO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'ALTERAÇÃO DE DADOS DE ALTERAÇÃO DE CARGO SALÁRIO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO ALTERAR DADOS DE ALTERAÇÃO DE CARGO SALÁRIO - CODIGO DO USUÁRIO: ' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'ALTERAÇÃO DE DADOS DE ALTERAÇÃO DE CARGO SALÁRIO';

			SELECT 
				CODIGO_ALTERACAO_CARGO_SALARIO,
				CODIGO_FUNCIONARIO,
				DATA,
				CODIGO_TIPO_CARGO,
				SALARIO,
				HORARIO_INICIO,
				HORARIO_FIM,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM TBVRT027_ALTERACAO_CARGO_SALARIO WHERE
				CODIGO_ALTERACAO_CARGO_SALARIO = @CODIGO_ALTERACAO_CARGO_SALARIO AND
				CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO
			RETURN
		END
END




GO


