USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT061_USUARIOS_PR_ALTERAR]    Script Date: 22/09/2014 02:04:33 ******/
DROP PROCEDURE [dbo].[SPVRT061_USUARIOS_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT061_USUARIOS_PR_ALTERAR]    Script Date: 22/09/2014 02:04:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT061_USUARIOS_PR_ALTERAR]
(
	@CODIGO_USUARIO			  int            =      NULL, 
	@NOME					  nvarchar(80)   =      NULL,
    @MAIL					  nvarchar(120)  =      NULL,
    @SENHA					  nvarchar(80)   =      NULL,
    @CODIGO_TIPO_ACESSO		  int            =      NULL,
	@CODIGO_STATUS			  int            =      NULL,
    @CODIGO_USUARIO_ALTERACAO int			 =      NULL,
    @DATA_ALTERACAO			  datetime       =      NULL
)
AS
BEGIN
	IF(@CODIGO_USUARIO IS NOT NULL)
		BEGIN
			UPDATE TBVRT001_USUARIOS SET
				NOME = @NOME,
				MAIL = @MAIL,
				SENHA = @SENHA,
				CODIGO_TIPO_ACESSO = @CODIGO_TIPO_ACESSO,
				CODIGO_STATUS = @CODIGO_STATUS,
				CODIGO_USUARIO_ALTERACAO = @CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO = @DATA_ALTERACAO
			WHERE
				CODIGO_USUARIO = @CODIGO_USUARIO
			
			DECLARE @DESC VARCHAR(120)

			IF(@@ERROR <>0)
				BEGIN

					SET @DESC = 'ERRO AO ALTERAR UM USUÁRIO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'ALTERAÇÃO DE USUÁRIO';

					SELECT @@ERROR as Erro, @DESC as Mensagem
					RETURN
				END
			ELSE
				BEGIN
			
					SET @DESC = 'SUCESSO AO ALTERAR UM USUÁRIO - CODIGO DO USUÁRIO: ' + CAST(@CODIGO_USUARIO AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'ALTERAÇÃO DE USUSUÁRIOUARIO';

					SELECT *, t1.DESCRICAO as STATUS_DESCRICAO FROM TBVRT001_USUARIOS t0 
					INNER JOIN TBVRT003_STATUS t1 ON t1.CODIGO_STATUS = t0.CODIGO_STATUS
					WHERE CODIGO_USUARIO = @CODIGO_USUARIO
					RETURN
				END
		END
END

GO


