USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT077_SISTEMA_PR_EXCLUIR]    Script Date: 16/09/2014 21:57:41 ******/
DROP PROCEDURE [dbo].[SPVRT077_SISTEMA_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT077_SISTEMA_PR_EXCLUIR]    Script Date: 16/09/2014 21:57:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT077_SISTEMA_PR_EXCLUIR]
(
	@CODIGO_SISTEMA		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_SISTEMA IS NOT NULL)
		BEGIN
			DECLARE @DESC VARCHAR(120)
			
			DELETE FROM TBVRT047_SISTEMA WHERE CODIGO_SISTEMA = @CODIGO_SISTEMA;
			IF(@@ERROR <>0)
				BEGIN

					SET @DESC = 'ERRO AO EXCLUIR UM SISTEMA - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE SISTEMA';

					SELECT @@ERROR as Erro, @DESC as Mensagem
					RETURN
				END
			ELSE
				BEGIN
			
					SET @DESC = 'SUCESSO AO EXCLUIR UM SISTEMA - CODIGO DO SISTEMA: ' + CAST(@CODIGO_SISTEMA AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE SISTEMA';
					RETURN
				END
				
		END
	ELSE
		BEGIN
			SELECT 'CODIGO NULO' as Erro, 'CÓDIGO NULO - NÃO FOI POSSÍVEL EXCLUIR' as Mensagem
					RETURN
		END
END
GO


