USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT080_ALTERACAO_CARGO_SALARIO_PR_EXCLUIR]    Script Date: 23/11/2014 21:29:06 ******/
DROP PROCEDURE [dbo].[SPVRT080_ALTERACAO_CARGO_SALARIO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT080_ALTERACAO_CARGO_SALARIO_PR_EXCLUIR]    Script Date: 23/11/2014 21:29:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE PROCEDURE [dbo].[SPVRT080_ALTERACAO_CARGO_SALARIO_PR_EXCLUIR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_ALTERACAO int = null,
	@CODIGO_ALTERACAO_CARGO_SALARIO	int = null
)
AS
BEGIN
	
	DECLARE @DESC VARCHAR(120);

	DELETE FROM TBVRT027_ALTERACAO_CARGO_SALARIO WHERE
	CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO AND CODIGO_ALTERACAO_CARGO_SALARIO = @CODIGO_ALTERACAO_CARGO_SALARIO

	IF(@@ERROR <>0)
						BEGIN

							SET @DESC = 'ERRO AO EXCLUIR ALTERACAO CARGO SALARIO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

							EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE ALTERACAO CARGO SALARIO';

							SELECT @@ERROR as Erro, @DESC as Mensagem
							RETURN
						END
					ELSE
						BEGIN
			
						SET @DESC = 'SUCESSO AO EXCLUIR ALTERACAO CARGO SALARIO - CODIGO DO FUNCIONARIO: ' + CAST(@CODIGO_FUNCIONARIO AS VARCHAR)

						EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE ALTERACAO CARGO SALARIO';
						
						SELECT
							ACS.CODIGO_ALTERACAO_CARGO_SALARIO,
							ACS.CODIGO_FUNCIONARIO,
							CONVERT(varchar, ACS.DATA, 103) AS DATA,
							ACS.CODIGO_TIPO_CARGO,
							TC.DESCRICAO AS TIPO_CARGO_DESCRICAO,
							ACS.SALARIO,
							ACS.HORARIO_INICIO,
							ACS.HORARIO_FIM,
							ACS.CODIGO_USUARIO_CADASTRO,
							ACS.DATA_CADASTRO,
							ACS.CODIGO_USUARIO_ALTERACAO,
							ACS.DATA_ALTERACAO,
							ACS.CODIGO_STATUS
						FROM 
							TBVRT027_ALTERACAO_CARGO_SALARIO ACS
							INNER JOIN TBVRT020_TIPO_CARGO TC
							ON TC.CODIGO_TIPO_CARGO = ACS.CODIGO_TIPO_CARGO WHERE
							CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

						RETURN
						END

	

	RETURN

END












GO


