USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT031_SINDICATO_PR_INCLUIR]    Script Date: 16/09/2014 21:57:32 ******/
DROP PROCEDURE [dbo].[SPVRT031_SINDICATO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT031_SINDICATO_PR_INCLUIR]    Script Date: 16/09/2014 21:57:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT031_SINDICATO_PR_INCLUIR]
(
	@NOME            nvarchar(80)   =      null,
    @CODIGO_USUARIO_CADASTRO int         =      null,
    @DATA_CADASTRO        datetime       =      null,
    @CODIGO_USUARIO_ALTERACAO int      =      null,
    @DATA_ALTERACAO     datetime       =      null,
    @CODIGO_STATUS        int            =      null
)
AS
BEGIN

	INSERT INTO TBVRT029_SINDICATO(
		NOME,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@NOME,
		@CODIGO_USUARIO_CADASTRO,
		@DATA_CADASTRO,
		@CODIGO_USUARIO_ALTERACAO,
		@DATA_ALTERACAO,
		@CODIGO_STATUS
	)


	
	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR UM SINDICATO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE SINDICATO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR UM SINDICATO - CODIGO DO SINDICATO' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE SINDICATO';

			SELECT * FROM  TBVRT029_SINDICATO
			WHERE CODIGO_SINDICATO = @ID
			RETURN
		END

END



GO


