USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT021_EMPRESA_PR_SELECIONAR]    Script Date: 04/10/2014 09:25:40 ******/
DROP PROCEDURE [dbo].[SPVRT021_EMPRESA_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT021_EMPRESA_PR_SELECIONAR]    Script Date: 04/10/2014 09:25:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SPVRT021_EMPRESA_PR_SELECIONAR]
(
	@CODIGO_EMPRESA				INT = NULL,
	@CNJP						NVARCHAR(14) = NULL,
	@RAZAO_SOCIAL				NVARCHAR(80) = NULL,
	@NOME_FANTASIA				NVARCHAR(80) = NULL,
	@INCRICAO_ESTADUAL			NVARCHAR(80) = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_STATUS				INT = NULL
)
AS
BEGIN

	SELECT
		CODIGO_EMPRESA,
		CNJP,
		RAZAO_SOCIAL,
		NOME_FANTASIA,
		INCRICAO_ESTADUAL,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	FROM 
		TBVRT030_EMPRESA
	WHERE
		(CODIGO_EMPRESA = @CODIGO_EMPRESA OR @CODIGO_EMPRESA IS NULL) 

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT030_EMPRESA.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT030_EMPRESA - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN

END







GO


