USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT078_FERIAS_PR_EXCLUIR]    Script Date: 16/11/2014 21:24:45 ******/
DROP PROCEDURE [dbo].[SPVRT078_FERIAS_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT078_FERIAS_PR_EXCLUIR]    Script Date: 16/11/2014 21:24:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE [dbo].[SPVRT078_FERIAS_PR_EXCLUIR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_ALTERACAO int = null,
	@CODIGO_FERIAS	int = null
)
AS
BEGIN
	
	DECLARE @DESC VARCHAR(120);

	DELETE FROM TBVRT025_FERIAS WHERE
	CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO AND CODIGO_FERIAS = @CODIGO_FERIAS

	IF(@@ERROR <>0)
						BEGIN

							SET @DESC = 'ERRO AO EXCLUIR FERIAS - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

							EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE FERIAS';

							SELECT @@ERROR as Erro, @DESC as Mensagem
							RETURN
						END
					ELSE
						BEGIN
			
						SET @DESC = 'SUCESSO AO EXCLUIR FERIAS - CODIGO DO FUNCIONARIO: ' + CAST(@CODIGO_FUNCIONARIO AS VARCHAR)

						EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE FERIAS';
						
						SELECT 
							CODIGO_FERIAS,
							CODIGO_FUNCIONARIO,
							CONVERT(varchar, DATA_PERIODO_INICIO, 103) AS DATA_PERIODO_INICIO,
							CONVERT(varchar, DATA_PERIODO_FIM, 103) AS DATA_PERIODO_FIM,
							CONVERT(varchar, DATA_GOZADA_INICIO, 103) AS DATA_GOZADA_INICIO,
							CONVERT(varchar, DATA_GOZADA_FIM, 103) AS DATA_GOZADA_FIM,
							CODIGO_USUARIO_CADASTRO,
							DATA_CADASTRO,
							CODIGO_USUARIO_ALTERACAO,
							DATA_ALTERACAO,
							CODIGO_STATUS
						FROM TBVRT025_FERIAS WHERE
							CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

						RETURN
						END

	

	RETURN

END









GO


