USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT011_DADOS_DEMISSAO_PR_ALTERAR]    Script Date: 04/10/2014 05:47:21 ******/
DROP PROCEDURE [dbo].[SPVRT011_DADOS_DEMISSAO_PR_ALTERAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT011_DADOS_DEMISSAO_PR_ALTERAR]    Script Date: 04/10/2014 05:47:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT011_DADOS_DEMISSAO_PR_ALTERAR]
(
    @CODIGO_DEMISSAO					INT				=	NULL,
	@CODIGO_FUNCIONARIO					int        =      null,
	@DATA_DEMISSAO					datetime       =      null,
	@DATA_REGISTRO					datetime       =      null,
	@CODIGO_TIPO_CARGO				int            =      null,
	@CODIGO_TIPO_SECAO				int            =      null,
	@SALARIO_INICIAL				nvarchar(80)   =      null,
	@COMISSAO						nvarchar(80)   =      null,
	@CODIGO_TIPO_TAREFA				int            =      null,
	@CODIGO_TIPO_FORMA_PAGAMENTO	int            =      null,
	@CODIGO_FORMA_PAGAMENTO			int            =      null,
	@CODIGO_USUARIO_CADASTRO		int            =      null,
	@DATA_CADASTRO					datetime       =      null,
	@CODIGO_USUARIO_ALTERACAO		int            =      null,
	@DATA_ALTERACAO					datetime       =      null,
	@CODIGO_STATUS					int            =      null
)
AS
BEGIN

	UPDATE TBVRT024_DADOS_DEMISSAO SET
		DATA_DEMISSAO = @DATA_DEMISSAO,
		DATA_REGISTRO = @DATA_REGISTRO,
		CODIGO_TIPO_CARGO = @CODIGO_TIPO_CARGO,
		CODIGO_TIPO_SECAO = @CODIGO_TIPO_SECAO,
		SALARIO_INICIAL = @SALARIO_INICIAL,
		COMISSAO = @COMISSAO,
		CODIGO_TIPO_TAREFA = @CODIGO_TIPO_TAREFA,
		CODIGO_TIPO_FORMA_PAGAMENTO = @CODIGO_TIPO_FORMA_PAGAMENTO,
		CODIGO_USUARIO_CADASTRO = @CODIGO_USUARIO_CADASTRO,
		CODIGO_USUARIO_ALTERACAO = @CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO = GETDATE(),
		CODIGO_STATUS = @CODIGO_STATUS
	WHERE
		CODIGO_DEMISSAO = @CODIGO_DEMISSAO AND
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO ALTERAR DADOS DE ADMISSÃO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'ALTERAÇÃO DE DADOS DE ADMISSÃO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO ALTERAR DADOS DE ADMISSÃO - CODIGO DO USUÁRIO' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'ALTERAÇÃO DE DADOS DE ADMISSÃO';

			SELECT CODIGO_USUARIO, NOME, MAIL, LOGIN_USUARIO FROM TBVRT001_USUARIOS
			WHERE CODIGO_USUARIO = @ID
			RETURN
		END
END





GO


