USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]    Script Date: 08/10/2014 16:26:27 ******/
DROP PROCEDURE [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]    Script Date: 08/10/2014 16:26:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]
( 
	@CODIGO_DEPENDENTE		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_DEPENDENTE IS NOT NULL)
		BEGIN
			IF((SELECT COUNT(0) FROM TBVRT045_BENEFICIO WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE) > 0)
			BEGIN
				DELETE FROM TBVRT045_BENEFICIO WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE
				DECLARE @DESC VARCHAR(120);
				IF(@@ERROR = 0)
				BEGIN
				SET @DESC = 'SUCESSO AO EXCLUIR UM BENEFÍCIO DE DEPENDENTE - CODIGO DO DEPENDENTE: ' + CAST(@CODIGO_DEPENDENTE AS VARCHAR)
					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE BENEFÍCIO';
					SELECT 200 AS Status, @DESC as Mensagem;
				END
				ELSE
				BEGIN					
					SET @DESC = 'ERRO AO EXCLUIR UM BENEFÍCIO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)
					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE BENEFÍCIO';
					SELECT 100 AS Status, @DESC as Mensagem;
				END
				RETURN;
			END
			ELSE
			BEGIN
				SET @DESC = 'NÃO EXISTEM BENEFÍCIOS ASSOCIADOS AO DEPENDENTE - CODIGO DO DEPENDENTE: ' + CAST(@CODIGO_DEPENDENTE AS VARCHAR)
				SELECT 300 AS Status, '' as Mensagem
				RETURN;
			END
		END
END

GO


