USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]    Script Date: 03/10/2014 06:17:56 ******/
DROP PROCEDURE [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]    Script Date: 03/10/2014 06:17:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SPVRT001_BENEFICIO_PR_EXCLUIR]
(
	@CODIGO_DEPENDENTE		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_DEPENDENTE IS NOT NULL)
		BEGIN
			IF((SELECT COUNT(0) FROM TBVRT045_BENEFICIO WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE) > 0)
			BEGIN
				DELETE FROM TBVRT045_BENEFICIO WHERE CODIGO_DEPENDENTE = @CODIGO_DEPENDENTE
				DECLARE @DESC VARCHAR(120);
				IF(@@ERROR = 0)
				BEGIN
				SET @DESC = 'SUCESSO AO EXCLUIR UM BENEFÍCIO - CODIGO DO BENEFÍCIO' + CAST(@CODIGO_DEPENDENTE AS VARCHAR)
					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', '' , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE BENEFÍCIO';
					SELECT 200 AS Mensagem;
				END
				ELSE
				BEGIN
					SELECT 100 AS Mensagem;
					SET @DESC = 'ERRO AO EXCLUIR UM BENEFÍCIO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)
					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE BENEFÍCIO';
				END
				RETURN;
			END
			ELSE
			BEGIN
				SELECT 300 AS Mensagem;
				RETURN;
			END
		END
END
GO


