USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]    Script Date: 03/10/2014 06:35:00 ******/
DROP PROCEDURE [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]    Script Date: 03/10/2014 06:35:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SPVRT068_FERIAS_PR_SELECIONAR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_CADASTRO int = null
)
AS
BEGIN

	SELECT
		CODIGO_FERIAS,
		CODIGO_FUNCIONARIO,
		DATA_PERIODO_INICIO,
		DATA_PERIODO_FIM,
		DATA_GOZADA_INICIO,
		DATA_GOZADA_FIM,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	FROM 
		TBVRT025_FERIAS
	WHERE
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT025_FERIAS.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT025_FERIAS - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'CONSULTA FERIAS';
			 
		END
	RETURN

END





GO


