USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT071_ACIDENTE_TRABALHO_PR_SELECIONAR]    Script Date: 21/11/2014 14:49:17 ******/
DROP PROCEDURE [dbo].[SPVRT071_ACIDENTE_TRABALHO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT071_ACIDENTE_TRABALHO_PR_SELECIONAR]    Script Date: 21/11/2014 14:49:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT071_ACIDENTE_TRABALHO_PR_SELECIONAR]
(
	@CODIGO_FUNCIONARIO					INT				=	NULL,
	@CODIGO_USUARIO_CADASTRO int = null
)
AS
BEGIN

	SELECT
		CODIGO_ACIDENTE_TRABALHO,
		CODIGO_FUNCIONARIO,
		CONVERT(varchar, DATA, 103) AS DATA,
		ACIDENTE_TRABALHO_LOCAL,
		CAUSA,
		CONVERT(varchar, DATA_ALTA, 103) AS DATA_ALTA,
		RESULTADO,
		OBSERVACOES,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	FROM 
		TBVRT026_ACIDENTE_TRABALHO
	WHERE
		CODIGO_FUNCIONARIO = @CODIGO_FUNCIONARIO

	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT026_ACIDENTE_TRABALHO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT026_ACIDENTE_TRABALHO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'CONSULTA ACIDENTES DE TRABALHO';
			 
		END
	RETURN

END






GO


