USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT030_SINDICATO_PR_EXCLUIR]    Script Date: 16/09/2014 21:57:41 ******/
DROP PROCEDURE [dbo].[SPVRT030_SINDICATO_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT030_SINDICATO_PR_EXCLUIR]    Script Date: 16/09/2014 21:57:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SPVRT030_SINDICATO_PR_EXCLUIR]
(
	@CODIGO_SINDICATO		 INT = NULL,
	@CODIGO_USUARIO_ALTERACAO INT = NULL
)
AS
BEGIN
	IF(@CODIGO_SINDICATO IS NOT NULL)
		BEGIN
			DECLARE @DESC VARCHAR(120)
			IF((SELECT COUNT(0) FROM TBVRT028_CONTRIBUICAO_SINDICAL where CODIGO_SINDICATO = @CODIGO_SINDICATO) <= 0)
				BEGIN
					DELETE FROM TBVRT029_SINDICATO WHERE CODIGO_SINDICATO = @CODIGO_SINDICATO;
					IF(@@ERROR <>0)
						BEGIN

							SET @DESC = 'ERRO AO EXCLUIR UM SINDICATO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

							EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE SINDICATO';

							SELECT @@ERROR as Erro, @DESC as Mensagem
							RETURN
						END
					ELSE
						BEGIN
			
							SET @DESC = 'SUCESSO AO EXCLUIR UM SINDICATO - CODIGO DO SINDICATO: ' + CAST(@CODIGO_SINDICATO AS VARCHAR)

							EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE SINDICATO';
							RETURN
						END
				END
			ELSE
				BEGIN
					SELECT 'RELACIONAMENTO' as Erro, 'RELACIONAMENTO COM CONTRIBUIÇÃO SINDICAL AINDA EXISTE' as Mensagem
					RETURN
				END
		END
	ELSE
		BEGIN
			SELECT 'CODIGO NULO' as Erro, 'CÓDIGO NULO - NÃO FOI POSSÍVEL EXCLUIR' as Mensagem
					RETURN
		END
END
GO


