USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT045_TIPO_CONTATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:05 ******/
DROP PROCEDURE [dbo].[SPVRT045_TIPO_CONTATO_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT045_TIPO_CONTATO_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



--TBVRT038_TIPO_CONTATO
CREATE PROCEDURE [dbo].[SPVRT045_TIPO_CONTATO_PR_SELECIONAR]
(
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@CODIGO_TIPO_CONTATO		 INT = NULL
)
AS
BEGIN
	SELECT * FROM TBVRT038_TIPO_CONTATO WHERE 
		(CODIGO_TIPO_CONTATO = @CODIGO_TIPO_CONTATO OR @CODIGO_TIPO_CONTATO IS NULL) 
	IF(@@ERROR <>0)
		BEGIN
			SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT038_TIPO_CONTATO.' as Mensagem
			
			DECLARE @DESC VARCHAR(120)

			SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT038_TIPO_CONTATO - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO';
			 
		END
	RETURN
END


GO


