USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT073_ALTERACAO_CARGO_SALARIO_PR_INCLUIR]    Script Date: 23/11/2014 21:30:31 ******/
DROP PROCEDURE [dbo].[SPVRT073_ALTERACAO_CARGO_SALARIO_PR_INCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT073_ALTERACAO_CARGO_SALARIO_PR_INCLUIR]    Script Date: 23/11/2014 21:30:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE PROCEDURE [dbo].[SPVRT073_ALTERACAO_CARGO_SALARIO_PR_INCLUIR]
(
    @CODIGO_ALTERACAO_CARGO_SALARIO		INT = NULL,
	@CODIGO_FUNCIONARIO					INT = NULL,
	@DATA								DATETIME = NULL,
	@CODIGO_TIPO_CARGO					INT = NULL,
	@SALARIO							NVARCHAR(80) = NULL,
	@HORARIO_INICIO						NVARCHAR(80) = NULL,
	@HORARIO_FIM						NVARCHAR(80) = NULL,
	@CODIGO_USUARIO_CADASTRO			INT = NULL,
	@DATA_CADASTRO						DATETIME = NULL,
	@CODIGO_USUARIO_ALTERACAO			INT = NULL,
	@DATA_ALTERACAO						DATETIME = NULL,
	@CODIGO_STATUS						INT = NULL
)
AS
BEGIN

	INSERT INTO TBVRT027_ALTERACAO_CARGO_SALARIO(
		CODIGO_FUNCIONARIO,
		DATA,
		CODIGO_TIPO_CARGO,
		SALARIO,
		HORARIO_INICIO,
		HORARIO_FIM,
		CODIGO_USUARIO_CADASTRO,
		DATA_CADASTRO,
		CODIGO_USUARIO_ALTERACAO,
		DATA_ALTERACAO,
		CODIGO_STATUS
	)
	VALUES(
		@CODIGO_FUNCIONARIO,
		@DATA,
		@CODIGO_TIPO_CARGO,
		@SALARIO,
		@HORARIO_INICIO,
		@HORARIO_FIM,
		@CODIGO_USUARIO_CADASTRO,
		GETDATE(),
		NULL,
		NULL,
		@CODIGO_STATUS
	)


	DECLARE @DESC VARCHAR(120);
	DECLARE @ID INT;
	SET @ID = @@IDENTITY;

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO INCLUIR DADOS DE ALTERAÇÃO DE CARGO SALÁRIO - CODIGO DO ERRO: ' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE ALTERAÇÃO DE CARGO SALÁRIO';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO INCLUIR DADOS DE ALTERAÇÃO DE CARGO SALÁRIO - CODIGO DO USUÁRIO: ' + CAST(@ID AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE DADOS DE ALTERAÇÃO DE CARGO SALÁRIO';

			SELECT
				ACS.CODIGO_ALTERACAO_CARGO_SALARIO,
				ACS.CODIGO_FUNCIONARIO,
				CONVERT(varchar, ACS.DATA, 103) AS DATA,
				ACS.CODIGO_TIPO_CARGO,
				TC.DESCRICAO AS TIPO_CARGO_DESCRICAO,
				ACS.SALARIO,
				ACS.HORARIO_INICIO,
				ACS.HORARIO_FIM,
				ACS.CODIGO_USUARIO_CADASTRO,
				ACS.DATA_CADASTRO,
				ACS.CODIGO_USUARIO_ALTERACAO,
				ACS.DATA_ALTERACAO,
				ACS.CODIGO_STATUS
			FROM 
				TBVRT027_ALTERACAO_CARGO_SALARIO ACS
				INNER JOIN TBVRT020_TIPO_CARGO TC
				ON TC.CODIGO_TIPO_CARGO = ACS.CODIGO_TIPO_CARGO WHERE
				 CODIGO_ALTERACAO_CARGO_SALARIO = @ID
			RETURN
		END
END







GO


