USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT022_ESTADO_CIVIL_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:22 ******/
DROP PROCEDURE [dbo].[SPVRT022_ESTADO_CIVIL_PR_SELECIONAR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT022_ESTADO_CIVIL_PR_SELECIONAR]    Script Date: 16/09/2014 21:58:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT022_ESTADO_CIVIL_PR_SELECIONAR]
(
	@CODIGO_ESTADO_CIVIL		 INT = NULL,
	@CODIGO_USUARIO_CADASTRO	INT = NULL,
	@DESCRICAO			 NVARCHAR(100) = NULL
)
AS
BEGIN
			
			SELECT 
				CODIGO_ESTADO_CIVIL,
				DESCRICAO,
				CODIGO_USUARIO_CADASTRO,
				DATA_CADASTRO,
				CODIGO_USUARIO_ALTERACAO,
				DATA_ALTERACAO,
				CODIGO_STATUS
			FROM TBVRT040_ESTADO_CIVIL
			WHERE 
				(CODIGO_ESTADO_CIVIL = @CODIGO_ESTADO_CIVIL OR @CODIGO_ESTADO_CIVIL IS NULL) AND
				(DESCRICAO = @DESCRICAO OR @DESCRICAO IS NULL)
			

			IF(@@ERROR <>0)
				BEGIN
					SELECT  @@ERROR as Erro, 'ERRO NO SELECT DA TABELA TBVRT040_ESTADO_CIVIL.' as Mensagem
					
					DECLARE @DESC VARCHAR(120)

					SET @DESC = 'ERRO NO SELECT DA TABELA TBVRT040_ESTADO_CIVIL - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

					EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_CADASTRO, 'INCLUSÃO DE USUÁRIO'; 
					
					 
				END
			RETURN
		
END




GO


