USE [DBVERITHUS]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT019_EMPRESA_PR_EXCLUIR]    Script Date: 28/11/2014 05:24:55 ******/
DROP PROCEDURE [dbo].[SPVRT019_EMPRESA_PR_EXCLUIR]
GO

/****** Object:  StoredProcedure [dbo].[SPVRT019_EMPRESA_PR_EXCLUIR]    Script Date: 28/11/2014 05:24:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SPVRT019_EMPRESA_PR_EXCLUIR]
(
	@CODIGO_EMPRESA				INT = NULL,
	@CODIGO_USUARIO_ALTERACAO	INT = NULL
)
AS
BEGIN
	IF(@CODIGO_EMPRESA IS NOT NULL)
		BEGIN
			DECLARE @DESC VARCHAR(120)
			IF((SELECT COUNT(0) FROM TBVRT030_EMPRESA where CODIGO_EMPRESA = @CODIGO_EMPRESA) <= 0)
			BEGIN
			DELETE FROM TBVRT030_EMPRESA WHERE CODIGO_EMPRESA = @CODIGO_EMPRESA

			

	IF(@@ERROR <>0)
		BEGIN

			SET @DESC = 'ERRO AO EXCLUIR UM EMPRESA - CODIGO DO ERRO' + CAST(@@ERROR AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'E', @DESC , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE EMPRESA';

			SELECT @@ERROR as Erro, @DESC as Mensagem
			RETURN
		END
	ELSE
		BEGIN
			
			SET @DESC = 'SUCESSO AO EXCLUIR UM EMPRESA - CODIGO DO ERRO' + CAST(@CODIGO_EMPRESA AS VARCHAR)

			EXEC dbo.SPVRT028_LOG_PR_INCLUIR 'A', '' , @CODIGO_USUARIO_ALTERACAO, 'EXCLUSÃO DE EMPRESA';
			RETURN
		END
		END
			ELSE
			BEGIN
				SELECT 'RELACIONAMENTO' as Erro, 'RELACIONAMENTO COM FUNCIONARIO AINDA EXISTE' as Mensagem
				RETURN
			END
		END
		
END





GO


