INSERT INTO [dbo].[TBVRT003_STATUS] (DESCRICAO) VALUES('Ativo')
INSERT INTO [dbo].[TBVRT003_STATUS] (DESCRICAO) VALUES('Inativo')
INSERT INTO [dbo].[TBVRT003_STATUS] (DESCRICAO) VALUES('Cancelado')
INSERT INTO [dbo].[TBVRT003_STATUS] (DESCRICAO) VALUES('Pendente')

select * from [dbo].[TBVRT003_STATUS]

